const fs = require('fs');

const data = [
  // ✈️ 旅遊觀光 - 機場與海關 (10)
  { category: "機場與海關", title: "入境審查", icon: "🛂", description: "海關詢問來訪目的與停留時間", dialogues: [ { speaker: "審查官", role: "staff", text: "滞在の目的は何ですか。", furigana: "滞[たい]在[ざい]の目[もく]的[てき]は何[なん]ですか。", translation: "停留的目的是什麼？", tags: ["N5", "敬語"] }, { speaker: "旅客", role: "user", text: "観光です。一週間滞在します。", furigana: "観[かん]光[こう]です。一[いっ]週[しゅう]間[かん]滞[たい]在[ざい]します。", translation: "觀光。會停留一個禮拜。", tags: ["N5", "敬語"] } ] },
  { category: "機場與海關", title: "提領行李", icon: "🧳", description: "尋找行李轉盤與確認行李", dialogues: [ { speaker: "旅客", role: "user", text: "すみません、JL802便のバゲージクレームはどこですか。", furigana: "すみません、JL802便[びん]のバゲージクレームはどこですか。", translation: "不好意思，請問JL802班機的行李轉盤在哪裡？", tags: ["N4", "敬語"] }, { speaker: "地勤", role: "staff", text: "あちらの3番テーブルになります。", furigana: "あちらの3番[ばん]テーブルになります。", translation: "在那邊的3號轉盤喔。", tags: ["N4", "敬語"] } ] },
  { category: "機場與海關", title: "物品申報", icon: "📝", description: "填寫海關申報單與確認違禁品", dialogues: [ { speaker: "海關", role: "staff", text: "申告するものはありますか。", furigana: "申[しん]告[こく]するものはありますか。", translation: "有要申報的物品嗎？", tags: ["N5", "敬語"] }, { speaker: "旅客", role: "user", text: "いいえ、ありません。お酒もタバコも持っていません。", furigana: "いいえ、ありません。お酒[さけ]もタバコも持[も]っていません。", translation: "沒有。我也沒有帶菸酒。", tags: ["N5", "敬語"] } ] },
  { category: "機場與海關", title: "尋找機場設施", icon: "🏧", description: "尋找廁所、外幣兌換處或租借Wi-Fi", dialogues: [ { speaker: "旅客", role: "user", text: "両替所はどこにありますか。", furigana: "両[りょう]替[がえ]所[じょ]はどこにありますか。", translation: "請問外幣兌換處在哪裡？", tags: ["N5", "敬語"] }, { speaker: "詢問處", role: "staff", text: "このエスカレーターを降りて右側にございます。", furigana: "このエスカレーターを降[お]りて右[みぎ]側[がわ]にございます。", translation: "搭這座手扶梯下去後在右手邊。", tags: ["N4", "謙讓語"] } ] },
  { category: "機場與海關", title: "轉機詢問", icon: "✈️", description: "確認轉機櫃檯與登機口", dialogues: [ { speaker: "旅客", role: "user", text: "乗り継ぎカウンターはどこですか。次のフライトはニューヨーク行きです。", furigana: "乗[の]り継[つ]ぎカウンターはどこですか。次[つぎ]のフライトはニューヨーク行[い]きです。", translation: "請問轉機櫃檯在哪裡？下一班飛機是飛往紐約的。", tags: ["N4", "敬語"] }, { speaker: "地勤", role: "staff", text: "まっすぐ進んで、緑の看板の案内に従ってください。", furigana: "まっすぐ進[すす]んで、緑[みどり]の看[かん]板[ばん]の案[あん]内[ない]に従[したが]ってください。", translation: "請直走，並跟隨綠色看板的指示。", tags: ["N4", "敬語"] } ] },
  { category: "機場與海關", title: "錯過班機求助", icon: "😰", description: "因延誤或其他原因錯過班機", dialogues: [ { speaker: "旅客", role: "user", text: "すみません、乗り遅れてしまいました。次の便に変更できますか。", furigana: "すみません、乗[の]り遅[おく]れてしまいました。次[つぎ]の便[びん]に変[へん]更[こう]できますか。", translation: "不好意思，我錯過班機了。可以更改到下一班嗎？", tags: ["N3", "敬語", "緊急"] }, { speaker: "地勤", role: "staff", text: "確認いたしますので、パスポートと搭乗券を見せていただけますか。", furigana: "確[かく]認[にん]いたしますので、パスポートと搭[とう]乗[じょう]券[けん]を見[み]せていただけますか。", translation: "我來確認一下，能讓我看一下您的護照和登機證嗎？", tags: ["N3", "謙讓語"] } ] },
  { category: "機場與海關", title: "行李損壞求償", icon: "👜", description: "領取行李時發現破損", dialogues: [ { speaker: "旅客", role: "user", text: "預けたスーツケースのキャスターが壊れているんですが。", furigana: "預[あず]けたスーツケースのキャスターが壊[こわ]れているんですが。", translation: "我託運的行李箱輪子壞掉了。", tags: ["N3", "敬語"] }, { speaker: "地勤", role: "staff", text: "大変申し訳ございません。破損状況を確認し、手続きをいたします。", furigana: "大[たい]変[へん]申[もう]し訳[わけ]ございません。破[は]損[そん]状[じょう]況[きょう]を確[かく]認[にん]し、手[て]続[づづ]きをいたします。", translation: "非常抱歉。我來確認破損狀況並為您辦理手續。", tags: ["N2", "謙讓語"] } ] },
  { category: "機場與海關", title: "購買免稅品", icon: "🛍️", description: "在免稅店購買菸酒或化妝品", dialogues: [ { speaker: "旅客", role: "user", text: "この香水、機内に持ち込めますか。", furigana: "この香[こう]水[すい]、機[き]内[ない]に持[も]ち込[こ]めますか。", translation: "這瓶香水可以帶上飛機嗎？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "はい、専用の袋で密封しますので、開封せずにお持ち込みください。", furigana: "はい、専[せん]用[よう]の袋[ふくろ]で密[みっ]封[ぷう]しますので、開[かい]封[ふう]せずにお持[も]ち込[こ]みください。", translation: "可以的，我們會用專用袋密封，請不要拆封直接帶上飛機。", tags: ["N3", "謙讓語"] } ] },
  { category: "機場與海關", title: "辦理登機與選位", icon: "💺", description: "要求靠窗或走道的座位", dialogues: [ { speaker: "旅客", role: "user", text: "通路側の席をお願いできますか。", furigana: "通[つう]路[ろ]側[がわ]の席[せき]をお願[ねが]いできますか。", translation: "可以麻煩給我靠走道的座位嗎？", tags: ["N4", "敬語"] }, { speaker: "地勤", role: "staff", text: "かしこまりました。本日は満席ですが、一つだけ空きがございました。", furigana: "かしこまりました。本[ほん]日[じつ]は満[まん]席[せき]ですが、一[ひと]つだけ空[あ]きがございました。", translation: "好的。今天雖然客滿，但剛好剩下一個空位。", tags: ["N3", "謙讓語"] } ] },
  { category: "機場與海關", title: "安檢沒收物品溝通", icon: "✂️", description: "安檢時物品被攔下", dialogues: [ { speaker: "安檢", role: "staff", text: "申し訳ありませんが、このハサミは機内持ち込み不可となっております。", furigana: "申[もう]し訳[わけ]ありませんが、このハサミは機[き]内[ない]持[も]ち込[こ]み不[ふ]可[か]となっております。", translation: "很抱歉，這把剪刀無法帶上飛機。", tags: ["N3", "敬語"] }, { speaker: "旅客", role: "user", text: "そうですか。それなら、ここで破棄してください。", furigana: "そうですか。それなら、ここで破[は]棄[き]してください。", translation: "這樣啊。那就在這裡丟掉吧。", tags: ["N4", "敬語"] } ] },

  // ✈️ 旅遊觀光 - 交通移動 (10)
  { category: "交通移動", title: "購買車票", icon: "🎫", description: "操作售票機與詢問交通卡", dialogues: [ { speaker: "旅客", role: "user", text: "新宿までの切符の買い方が分かりません。", furigana: "新[しん]宿[じゅく]までの切[きっ]符[ぷ]の買[か]い方[かた]が分[わ]かりません。", translation: "我不知道去新宿的車票怎麼買。", tags: ["N4", "敬語"] }, { speaker: "站務員", role: "staff", text: "あちらの券売機で、画面を英語に切り替えられますよ。", furigana: "あちらの券[けん]売[ばい]機[き]で、画[が]面[めん]を英[えい]語[ご]に切[き]り替[か]えられますよ。", translation: "在那邊的售票機，可以把畫面切換成英文喔。", tags: ["N4", "敬語"] } ] },
  { category: "交通移動", title: "詢問路線與轉乘", icon: "🗺️", description: "確認月台與抵達時間", dialogues: [ { speaker: "旅客", role: "user", text: "この電車は秋葉原に止まりますか。", furigana: "この電[でん]車[しゃ]は秋[あき]葉[は]原[ばら]に止[と]まりますか。", translation: "這班電車會停秋葉原嗎？", tags: ["N5", "敬語"] }, { speaker: "站務員", role: "staff", text: "いいえ、快速は止まりません。次の普通電車にお乗りください。", furigana: "いいえ、快[かい]速[そく]は止[と]まりません。次[つぎ]の普[ふつう]通[つう]電[でん]車[しゃ]にお乗[の]りください。", translation: "不會，快速列車不停。請搭乘下一班普通車。", tags: ["N4", "敬語"] } ] },
  { category: "交通移動", title: "搭乘計程車", icon: "🚕", description: "指示目的地與結帳", dialogues: [ { speaker: "旅客", role: "user", text: "東京タワーまでお願いします。", furigana: "東[とう]京[きょう]タワーまでお願[ねが]いします。", translation: "麻煩到東京鐵塔。", tags: ["N5", "敬語"] }, { speaker: "司機", role: "staff", text: "かしこまりました。シートベルトをお締めください。", furigana: "かしこまりました。シートベルトをお締[し]めください。", translation: "好的。請繫上安全帶。", tags: ["N4", "謙讓語"] } ] },
  { category: "交通移動", title: "租車與還車", icon: "🚗", description: "辦理租車手續與還車確認", dialogues: [ { speaker: "旅客", role: "user", text: "ネットで予約した王です。国際免許証はこちらです。", furigana: "ネットで予[よ]約[やく]した王[おう]です。国[こく]際[さい]免[めん]許[きょ]証[しょう]はこちらです。", translation: "我是網路上預約的王。這是我的國際駕照。", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "ありがとうございます。ガソリンは満タンにしてご返却ください。", furigana: "ありがとうございます。ガソリンは満[まん]タンにしてご返[へん]却[きゃく]ください。", translation: "謝謝您。還車時請將油箱加滿。", tags: ["N3", "敬語"] } ] },
  { category: "交通移動", title: "搭錯車補票", icon: "🎟️", description: "坐過站或搭錯車種", dialogues: [ { speaker: "旅客", role: "user", text: "間違えて特急に乗ってしまいました。ここで精算できますか。", furigana: "間[ま]違[ちが]えて特[とっ]急[きゅう]に乗[の]ってしまいました。ここで精[せい]算[さん]できますか。", translation: "我不小心搭到特急列車了。可以在這裡補票嗎？", tags: ["N3", "敬語"] }, { speaker: "站務員", role: "staff", text: "はい、特急料金の追加で500円になります。", furigana: "はい、特[とっ]急[きゅう]料[りょう]金[きん]の追[つい]加[か]で500円[えん]になります。", translation: "可以，特急費用需要追加500日圓。", tags: ["N4", "敬語"] } ] },
  { category: "交通移動", title: "IC卡儲值與退卡", icon: "💳", description: "西瓜卡沒錢或準備回國退卡", dialogues: [ { speaker: "旅客", role: "user", text: "Suicaのチャージが足りないみたいで、改札で止められました。", furigana: "Suicaのチャージが足[た]りないみたいで、改[かい]札[さつ]で止[と]められました。", translation: "我的西瓜卡好像餘額不足，被驗票閘門擋下來了。", tags: ["N3", "敬語", "被動態"] }, { speaker: "站務員", role: "staff", text: "あちらの精算機でチャージしてから、もう一度タッチしてください。", furigana: "あちらの精[せい]算[さん]機[き]でチャージしてから、もう一[いち]度[ど]タッチしてください。", translation: "請在那邊的精算機儲值後，再感應一次。", tags: ["N4", "敬語"] } ] },
  { category: "交通移動", title: "公車投幣與下車", icon: "🚌", description: "確認公車是否到達目的地與付款方式", dialogues: [ { speaker: "旅客", role: "user", text: "すみません、このバスは金閣寺に行きますか。", furigana: "すみません、このバスは金[きん]閣[かく]寺[じ]に行[い]きますか。", translation: "不好意思，請問這班公車有到金閣寺嗎？", tags: ["N5", "敬語"] }, { speaker: "司機", role: "staff", text: "はい、行きますよ。降りる時に前からお支払いください。", furigana: "はい、行[い]きますよ。降[お]りる時[とき]に前[まえ]からお支[しはら]いください。", translation: "有的。下車時請從前門付費。", tags: ["N4", "敬語"] } ] },
  { category: "交通移動", title: "新幹線便當購買", icon: "🍱", description: "在月台或車廂內買火車便當", dialogues: [ { speaker: "旅客", role: "user", text: "幕の内弁当と緑茶をお願いします。", furigana: "幕[まく]の内[うち]弁[べん]当[とう]と緑[りょく]茶[ちゃ]をお願[ねが]いします。", translation: "請給我幕之內便當和綠茶。", tags: ["N5", "敬語"] }, { speaker: "店員", role: "staff", text: "お箸とお手拭きはお付けしますか。", furigana: "お箸[はし]とお手[て]拭[ふき]はお付[つ]けしますか。", translation: "需要附上筷子和濕紙巾嗎？", tags: ["N4", "敬語"] } ] },
  { category: "交通移動", title: "腳踏車租借", icon: "🚲", description: "詢問租借腳踏車的費用與歸還", dialogues: [ { speaker: "旅客", role: "user", text: "自転車を一日借りたいんですが、いくらですか。", furigana: "自[じ]転[てん]車[しゃ]を一[いち]日[にち]借[か]りたいんですが、いくらですか。", translation: "我想租一天的腳踏車，請問多少錢？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "1日1000円です。夜8時までに返却をお願いします。", furigana: "1日[にち]1000円[えん]です。夜[よる]8時[じ]までに返[へん]却[きゃく]をお願[ねが]いします。", translation: "一天1000日圓。請在晚上8點前歸還。", tags: ["N4", "敬語"] } ] },
  { category: "交通移動", title: "遇到電車誤點", icon: "⏱️", description: "確認電車延誤情況", dialogues: [ { speaker: "旅客", role: "user", text: "人身事故で電車が止まっているようですが、いつ動きますか。", furigana: "人[じん]身[しん]事[じ]故[こ]で電[でん]車[しゃ]が止[と]まっているようですが、いつ動[うご]きますか。", translation: "好像因為人身事故電車停駛了，什麼時候會開呢？", tags: ["N3", "敬語", "緊急"] }, { speaker: "站務員", role: "staff", text: "現在復旧作業中で、運転再開は未定となっております。", furigana: "現[げん]在[ざい]復[ふっ]旧[きゅう]作[さく]業[ぎょう]中[ちゅう]で、運[うん]転[てん]再[さい]開[かい]は未[み]定[てい]となっております。", translation: "目前正在進行修復作業，恢復行駛的時間尚未確定。", tags: ["N2", "謙讓語"] } ] },

  // ✈️ 旅遊觀光 - 飯店住宿 (10)
  { category: "飯店住宿", title: "辦理入住", icon: "🏨", description: "Check-in手續與確認資料", dialogues: [ { speaker: "櫃台", role: "staff", text: "いらっしゃいませ。ご予約のお名前をお願いします。", furigana: "いらっしゃいませ。ご予[よ]約[やく]のお名[な]前[まえ]をお願[ねが]いします。", translation: "歡迎光臨。請給我您預約的姓名。", tags: ["N4", "敬語"] }, { speaker: "旅客", role: "user", text: "林です。3泊で予約しています。", furigana: "林[はやし]です。3泊[はく]で予[よ]約[やく]しています。", translation: "我姓林。預約了三個晚上。", tags: ["N5", "敬語"] } ] },
  { category: "飯店住宿", title: "詢問設施", icon: "♨️", description: "詢問溫泉、早餐時間或大廳設備", dialogues: [ { speaker: "旅客", role: "user", text: "朝食は何時からですか。あと、大浴場はどこですか。", furigana: "朝[ちょう]食[しょく]は何[なん]時[じ]からですか。あと、大[だい]浴[よく]場[じょう]はどこですか。", translation: "早餐是從幾點開始？還有大浴場在哪裡？", tags: ["N5", "敬語"] }, { speaker: "櫃台", role: "staff", text: "朝食は7時から1階のレストランで、大浴場は2階にございます。", furigana: "朝[ちょう]食[しょく]は7時[じ]から1階[かい]のレストランで、大[だい]浴[よく]場[じょう]は2階[かい]にございます。", translation: "早餐7點開始在一樓餐廳，大浴場位於二樓。", tags: ["N4", "謙讓語"] } ] },
  { category: "飯店住宿", title: "客房服務", icon: "🛎️", description: "索取毛巾、備品或點餐", dialogues: [ { speaker: "旅客", role: "user", text: "タオルの替えを部屋まで持ってきてもらえますか。", furigana: "タオルの替[か]えを部[へ]屋[や]まで持[も]ってきてもらえますか。", translation: "可以請你們送替換的毛巾到房間來嗎？", tags: ["N4", "敬語"] }, { speaker: "客服", role: "staff", text: "かしこまりました。すぐにお持ちいたします。", furigana: "かしこまりました。すぐにお持[も]ちいたします。", translation: "好的。馬上為您送去。", tags: ["N4", "謙讓語"] } ] },
  { category: "飯店住宿", title: "寄放行李", icon: "🎒", description: "入住前或退房後寄放行李", dialogues: [ { speaker: "旅客", role: "user", text: "チェックアウト後ですが、夕方まで荷物を預かってもらえますか。", furigana: "チェックアウト後[あと]ですが、夕[ゆう]方[がた]まで荷[に]物[もつ]を預[あず]かってもらえますか。", translation: "雖然已經退房了，但能幫我寄放行李到傍晚嗎？", tags: ["N4", "敬語"] }, { speaker: "櫃台", role: "staff", text: "はい、承知いたしました。こちらの番号札をお持ちください。", furigana: "はい、承[しょう]知[ち]いたしました。こちらの番[ばん]号[ごう]札[ふだ]をお持[も]ちください。", translation: "好的，了解了。請保管好這張號碼牌。", tags: ["N4", "謙讓語"] } ] },
  { category: "飯店住宿", title: "要求換房間", icon: "🛏️", description: "房間有異味或設施損壞", dialogues: [ { speaker: "旅客", role: "user", text: "部屋がタバコ臭いんですが、禁煙室に変えてもらえませんか。", furigana: "部[へ]屋[や]がタバコ臭[くさ]いんですが、禁[きん]煙[えん]室[しつ]に変[か]えてもらえませんか。", translation: "房間裡有菸味，能幫我換到禁菸房嗎？", tags: ["N3", "敬語"] }, { speaker: "櫃台", role: "staff", text: "申し訳ございません。すぐに別の禁煙ルームをご用意いたします。", furigana: "申[もう]し訳[わけ]ございません。すぐに別[べつ]の禁[きん]煙[えん]ルームをご用[よう]意[い]いたします。", translation: "非常抱歉。我們馬上為您準備另一間禁菸房。", tags: ["N3", "謙讓語"] } ] },
  { category: "飯店住宿", title: "借用轉接頭與充電線", icon: "🔌", description: "詢問是否有萬用轉接頭", dialogues: [ { speaker: "旅客", role: "user", text: "携帯の充電器か変換プラグを借りることはできますか。", furigana: "携[けい]帯[たい]の充[じゅう]電[でん]器[き]か変[へん]換[かん]プラグを借[か]りることはできますか。", translation: "可以跟你們借手機充電器或轉接頭嗎？", tags: ["N4", "敬語"] }, {フロント: "櫃台", role: "staff", text: "はい、フロントにて貸し出しております。iPhone用でよろしいですか。", furigana: "はい、フロントにて貸[か]し出[だ]しております。iPhone用[よう]でよろしいですか。", translation: "可以，櫃台有提供租借。是iPhone用的對嗎？", tags: ["N4", "敬語"] } ] },
  { category: "飯店住宿", title: "投訴噪音", icon: "🔊", description: "隔壁房間太吵", dialogues: [ { speaker: "旅客", role: "user", text: "隣の部屋の人たちが騒がしくて、眠れないんですが。", furigana: "隣[となり]の部[へ]屋[や]の人[ひと]たちが騒[さわ]がしくて、眠[ねむ]れないんですが。", translation: "隔壁房間的人太吵了，讓我睡不著。", tags: ["N3", "敬語"] }, { speaker: "櫃台", role: "staff", text: "ご迷惑をおかけしております。すぐにスタッフが注意に向かいます。", furigana: "ご迷[めい]惑[わく]をおかけしております。すぐにスタッフが注[ちゅう]意[い]に向[む]かいます。", translation: "造成您的困擾了。我們馬上派工作人員過去提醒。", tags: ["N3", "謙讓語"] } ] },
  { category: "飯店住宿", title: "延遲退房請求", icon: "⏰", description: "想晚一點退房 (Late Check-out)", dialogues: [ { speaker: "旅客", role: "user", text: "チェックアウトの時間を1時間延長したいんですが、可能ですか。", furigana: "チェックアウトの時[じ]間[かん]を1時[じ]間[かん]延[えん]長[ちょう]したいんですが、可[か]能[のう]ですか。", translation: "我想把退房時間延長一個小時，請問可以嗎？", tags: ["N3", "敬語"] }, { speaker: "櫃台", role: "staff", text: "はい、可能ですが、延長料金が1000円かかります。", furigana: "はい、可[か]能[のう]ですが、延[えん]長[ちょう]料[りょう]金[きん]が1000円[えん]かかります。", translation: "可以的，但需要酌收1000日圓的延長費用。", tags: ["N4", "敬語"] } ] },
  { category: "飯店住宿", title: "詢問接駁車", icon: "🚌", description: "確認去機場或車站的接駁車時間", dialogues: [ { speaker: "旅客", role: "user", text: "空港行きのシャトルバスは、予約が必要ですか。", furigana: "空[くう]港[こう]行[い]きのシャトルバスは、予[よ]約[やく]が必[ひつ]要[よう]ですか。", translation: "請問去機場的接駁車需要預約嗎？", tags: ["N4", "敬語"] }, { speaker: "櫃台", role: "staff", text: "はい、前日の夜までにご予約をお願いしております。", furigana: "はい、前[ぜん]日[じつ]の夜[よる]までにご予[よ]約[やく]をお願[ねが]いしております。", translation: "是的，麻煩請在前一天晚上前完成預約。", tags: ["N3", "謙讓語"] } ] },
  { category: "飯店住宿", title: "洗衣服務", icon: "👕", description: "詢問投幣洗衣機或送洗服務", dialogues: [ { speaker: "旅客", role: "user", text: "ホテルの中にコインランドリーはありますか。", furigana: "ホテルの中[なか]にコインランドリーはありますか。", translation: "飯店裡面有投幣式洗衣機嗎？", tags: ["N5", "敬語"] }, { speaker: "櫃台", role: "staff", text: "申し訳ありません。ランドリーサービスのみ承っております。", furigana: "申[もう]し訳[わけ]ありません。ランドリーサービスのみ承[うけたまわ]っております。", translation: "非常抱歉。我們只有提供送洗服務。", tags: ["N3", "謙讓語"] } ] },

  // ✈️ 旅遊觀光 - 餐飲點餐 (10)
  { category: "餐飲點餐", title: "預約餐廳", icon: "☎️", description: "打電話預約人數與時間", dialogues: [ { speaker: "旅客", role: "user", text: "今日の夜7時に、3名で予約したいのですが。", furigana: "今[きょう]日[の]の夜[よる]7時[じ]に、3名[めい]で予[よ]約[やく]したいのですが。", translation: "我想要預約今天晚上7點，總共三位。", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "申し訳ありません、本日はすでに満席となっております。", furigana: "申[もう]し訳[わけ]ありません、本[ほん]日[じつ]はすでに満[まん]席[せき]となっております。", translation: "非常抱歉，今天已經客滿了。", tags: ["N3", "謙讓語"] } ] },
  { category: "餐飲點餐", title: "索取菜單", icon: "📖", description: "入座後索取外文菜單與推薦菜色", dialogues: [ { speaker: "旅客", role: "user", text: "すみません、英語のメニューはありますか。", furigana: "すみません、英[えい]語[ご]のメニューはありますか。", translation: "不好意思，請問有英文菜單嗎？", tags: ["N5", "敬語"] }, { speaker: "店員", role: "staff", text: "はい、こちらになります。ご注文がお決まりになりましたらお呼びください。", furigana: "はい、こちらになります。ご注[ちゅう]文[もん]がお決[き]まりになりましたらお呼[よ]びください。", translation: "有的，這邊請。決定好餐點的話請再叫我。", tags: ["N4", "敬語"] } ] },
  { category: "餐飲點餐", title: "特殊飲食需求", icon: "🥗", description: "表達吃素或對特定食物過敏", dialogues: [ { speaker: "旅客", role: "user", text: "甲殻類アレルギーなのですが、このスープにエビは入っていますか。", furigana: "甲[こう]殻[かく]類[るい]アレルギーなのですが、このスープにエビは入[はい]っていますか。", translation: "我對甲殼類過敏，這碗湯裡面有蝦子嗎？", tags: ["N3", "敬語"] }, { speaker: "店員", role: "staff", text: "エビの出汁を使用しております。別のメニューをご案内しましょうか。", furigana: "エビの出[だ]汁[し]を使[し]用[よう]しております。別[べつ]のメニューをご案[あん]内[ない]しましょうか。", translation: "裡面有用到蝦子熬高湯。需要為您介紹其他餐點嗎？", tags: ["N3", "謙讓語"] } ] },
  { category: "餐飲點餐", title: "結帳與索取收據", icon: "💳", description: "飯後結帳與發票處理", dialogues: [ { speaker: "旅客", role: "user", text: "お会計お願いします。クレジットカードは使えますか。", furigana: "お会[かい]計[けい]お願[ねが]いします。クレジットカードは使[つか]えますか。", translation: "麻煩結帳。可以刷信用卡嗎？", tags: ["N5", "敬語"] }, { speaker: "店員", role: "staff", text: "はい、ご利用いただけます。領収書は必要ですか。", furigana: "はい、ご利[り]用[よう]いただけます。領[りょう]収[しゅう]書[しょ]は必[ひつ]要[よう]ですか。", translation: "可以的。需要開立收據嗎？", tags: ["N5", "敬語"] } ] },
  { category: "餐飲點餐", title: "要求分開結帳", icon: "🧾", description: "個別会計 (各付各的)", dialogues: [ { speaker: "旅客", role: "user", text: "お会計は別々にしてもらえますか。", furigana: "お会[かい]計[けい]は別々[べつべつ]にしてもらえますか。", translation: "請問可以分開結帳嗎？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "申し訳ございません、当店では個別会計はお断りしております。", furigana: "申[もう]し訳[わけ]ございません、当[とう]店[てん]では個[こ]別[べつ]会[かい]計[けい]はお断[ことわ]りしております。", translation: "非常抱歉，本店不提供分開結帳的服務。", tags: ["N3", "謙讓語"] } ] },
  { category: "餐飲點餐", title: "食物打包外帶", icon: "🥡", description: "吃不完想打包帶走", dialogues: [ { speaker: "旅客", role: "user", text: "残った料理を持ち帰ることはできますか。", furigana: "残[のこ]った料[りょう]理[り]を持[も]ち帰[かえ]ることはできますか。", translation: "請問剩下的料理可以打包帶走嗎？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "衛生上の理由で、お持ち帰りはご遠慮いただいております。", furigana: "衛[えい]生[せい]上[じょう]の理[り]由[ゆう]で、お持[も]ち帰[かえ]りはご遠[えん]慮[りょ]いただいております。", translation: "基於衛生考量，我們婉拒打包外帶服務。", tags: ["N2", "謙讓語"] } ] },
  { category: "餐飲點餐", title: "追加點餐", icon: "🍺", description: "吃飯中途想要加點飲料或小菜", dialogues: [ { speaker: "旅客", role: "user", text: "すみません、生ビールもう一杯と、枝豆を追加でお願いします。", furigana: "すみません、生[なま]ビールもう一[いっ]杯[ぱい]と、枝[えだ]豆[まめ]を追[つい]加[か]でお願[ねが]いします。", translation: "不好意思，我要追加一杯生啤酒和一份毛豆。", tags: ["N5", "敬語"] }, { speaker: "店員", role: "staff", text: "生ビールと枝豆ですね。少々お待ちください。", furigana: "生[なま]ビールと枝[えだ]豆[まめ]ですね。少々[しょうしょう]お待[ま]ちください。", translation: "生啤酒跟毛豆對吧。請稍候。", tags: ["N5", "敬語"] } ] },
  { category: "餐飲點餐", title: "詢問用餐時間限制", icon: "⏳", description: "吃到飽或熱門餐廳確認用餐時長", dialogues: [ { speaker: "旅客", role: "user", text: "食事の時間は何時間制ですか。", furigana: "食[しょく]事[じ]の時[じ]間[かん]は何[なん]時[じ]間[かん]制[せい]ですか。", translation: "請問用餐時間限制是幾個小時？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "当店は90分制となっております。ラストオーダーは30分前です。", furigana: "当[とう]店[てん]は90分[ぷん]制[せい]となっております。ラストオーダーは30分[ぷん]前[まえ]です。", translation: "本店為90分鐘制。最後點餐時間為結束前30分鐘。", tags: ["N3", "敬語"] } ] },
  { category: "餐飲點餐", title: "確認餐點還沒來", icon: "🍽️", description: "等很久了菜還沒上", dialogues: [ { speaker: "旅客", role: "user", text: "あの、注文した唐揚げがまだ来てないんですが。", furigana: "あの、注[ちゅう]文[もん]した唐[から]揚[あ]げがまだ来[き]てないんですが。", translation: "那個，我們點的唐揚雞還沒來...", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "大変失礼いたしました。すぐに厨房に確認してまいります。", furigana: "大[たい]変[へん]失[しつ]礼[れい]いたしました。すぐに厨[ちゅう]房[ぼう]に確[かく]認[にん]してまいります。", translation: "非常抱歉。我馬上去廚房確認。", tags: ["N3", "謙讓語"] } ] },
  { category: "餐飲點餐", title: "詢問招牌菜", icon: "⭐", description: "不知道吃什麼時請店員推薦", dialogues: [ { speaker: "旅客", role: "user", text: "このお店のおすすめ料理は何ですか。", furigana: "このおお店[みせ]のおすすめ料[りょう]理[り]は何[なん]ですか。", translation: "這家店的推薦料理是什麼？", tags: ["N5", "敬語"] }, { speaker: "店員", role: "staff", text: "こちらの和牛ハンバーグが一番人気です。", furigana: "こちらの和[わ]牛[ぎゅう]ハンバーグが一[いち]番[ばん]人[にん]気[き]です。", translation: "這份和牛漢堡排是我們最受歡迎的餐點。", tags: ["N5", "敬語"] } ] },

  // ✈️ 旅遊觀光 - 購物消費 (10)
  { category: "購物消費", title: "尋找特定商品", icon: "🔍", description: "拿照片詢問店員商品位置", dialogues: [ { speaker: "顧客", role: "user", text: "すみません、この写真の化粧品を探しているんですが。", furigana: "すみません、この写[しゃ]真[しん]の化[け]粧[しょう]品[ひん]を探[さが]しているんですが。", translation: "不好意思，我在找照片上的這款化妝品。", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "そちらでしたら、3番の棚にございます。ご案内します。", furigana: "そちらでしたら、3番[ばん]の棚[たな]にございます。ご案[あん]内[ない]します。", translation: "那個的話在3號貨架上。我帶您去。", tags: ["N4", "敬語"] } ] },
  { category: "購物消費", title: "試穿尺寸", icon: "👕", description: "詢問試衣間與其他尺碼", dialogues: [ { speaker: "顧客", role: "user", text: "これ試着してもいいですか。あと、Mサイズはありますか。", furigana: "これ試[し]着[ちゃく]してもいいですか。あと、Mサイズはありますか。", translation: "這個可以試穿嗎？還有，有M號的嗎？", tags: ["N5", "敬語"] }, { speaker: "店員", role: "staff", text: "はい、試着室へどうぞ。Mサイズをお持ちしますね。", furigana: "はい、試[し]着[ちゃく]室[しつ]へどうぞ。Mサイズをお持[も]ちしますね。", translation: "可以，請到試衣間。我幫您拿M號過來。", tags: ["N5", "敬語"] } ] },
  { category: "購物消費", title: "詢問折扣與庫存", icon: "🏷️", description: "確認特價商品與是否還有庫存", dialogues: [ { speaker: "顧客", role: "user", text: "この商品はセール対象ですか。別の色はありますか。", furigana: "この商[しょう]品[ひん]はセール対[たい]象[しょう]ですか。別[べつ]の色[いろ]はありますか。", translation: "這個商品有打折嗎？有別的顏色嗎？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "申し訳ありません、こちらは新作でして…。お色もこれだけになります。", furigana: "申[もう]し訳[わけ]ありません、こちらは新[しん]作[さく]でして…。お色[いろ]もこれだけになります。", translation: "非常抱歉，這是新款... 顏色也只有這一種了。", tags: ["N3", "敬語"] } ] },
  { category: "購物消費", title: "辦理退稅", icon: "🛂", description: "結帳時辦理 Tax-free", dialogues: [ { speaker: "顧客", role: "user", text: "免税でお願いします。", furigana: "免[めん]税[ぜい]でお願[ねが]いします。", translation: "請幫我辦理免稅。", tags: ["N5", "敬語"] }, { speaker: "店員", role: "staff", text: "かしこまりました。パスポートのご提示をお願いいたします。", furigana: "かしこまりました。パスポートのご提[てい]示[じ]をお願[ねが]いいたします。", translation: "好的。麻煩請出示您的護照。", tags: ["N4", "謙讓語"] } ] },
  { category: "購物消費", title: "衣服退換貨交涉", icon: "🔄", description: "買錯尺寸想要換貨", dialogues: [ { speaker: "顧客", role: "user", text: "昨日買ったこの服、サイズが合わなかったので交換できますか。", furigana: "昨[きのう]日[のう]買[か]ったこの服[ふく]、サイズが合[あ]わなかったので交[こう]換[かん]できますか。", translation: "昨天買的這件衣服尺寸不合，可以換貨嗎？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "レシートはお持ちでしょうか。タグが付いた状態なら可能です。", furigana: "レシートはお持[も]ちでしょうか。タグが付[つ]いた状[じょう]態[たい]なら可[か]能[のう]です。", translation: "請問您有帶收據嗎？如果標籤還在的話就可以更換。", tags: ["N3", "敬語"] } ] },
  { category: "購物消費", title: "詢問保固與海外維修", icon: "🔧", description: "買相機或電器確認保固", dialogues: [ { speaker: "顧客", role: "user", text: "このカメラ、海外でも保証は効きますか。", furigana: "このカメラ、海[かい]外[がい]でも保[ほ]証[しょう]は効[き]きますか。", translation: "這台相機在海外也有保固嗎？", tags: ["N3", "敬語"] }, { speaker: "店員", role: "staff", text: "こちらは国内限定モデルですので、海外での修理は有料になります。", furigana: "こちらは国[こく]内[ない]限[げん]定[てい]モデルですので、海[かい]外[がい]での修[しゅう]理[り]は有[ゆう]料[りょう]になります。", translation: "這款是國內限定型號，所以在海外維修會需要付費。", tags: ["N2", "敬語"] } ] },
  { category: "購物消費", title: "要求包裝成禮物", icon: "🎁", description: "送禮用的包裝服務", dialogues: [ { speaker: "顧客", role: "user", text: "友達へのプレゼントなんですが、ラッピングしてもらえますか。", furigana: "友[とも]達[だち]へのプレゼントなんですが、ラッピングしてもらえますか。", translation: "這是要送朋友的禮物，可以幫我包裝嗎？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "無料の袋と、有料の箱がございますが、どちらになさいますか。", furigana: "無[む]料[りょう]の袋[ふくろ]と、有[ゆう]料[りょう]の箱[はこ]がございますが、どちらになさいますか。", translation: "我們有免費的袋子跟要付費的盒子，請問您需要哪一種？", tags: ["N3", "謙讓語"] } ] },
  { category: "購物消費", title: "電器配送至機場", icon: "📦", description: "買了大型電器請店家寄到機場", dialogues: [ { speaker: "顧客", role: "user", text: "これを成田空港まで配送してもらうことはできますか。", furigana: "これを成[なり]田[た]空[くう]港[こう]まで配[はい]送[そう]してもらうことはできますか。", translation: "可以麻煩把這個配送到成田機場嗎？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "はい、送料が別途かかりますが、明後日の到着で手配可能です。", furigana: "はい、送[そう]料[りょう]が別[べっ]途[と]かかりますが、明[あさ]後[って]日[の]の到[とう]着[ちゃく]で手[て]配[はい]可[か]能[のう]です。", translation: "可以的，雖然需要額外運費，但可以安排在後天送達。", tags: ["N3", "敬語"] } ] },
  { category: "購物消費", title: "詢問是否能試吃", icon: "🍡", description: "在土產店看到有趣的點心", dialogues: [ { speaker: "顧客", role: "user", text: "このお菓子、試食することはできますか。", furigana: "このお菓[か]子[し]、試[し]食[しょく]することはできますか。", translation: "請問這個點心可以試吃嗎？", tags: ["N5", "敬語"] }, { speaker: "店員", role: "staff", text: "はい、どうぞ。そちらは抹茶味でございます。", furigana: "はい、どうぞ。そちらは抹[まっ]茶[ちゃ]味[あじ]でございます。", translation: "可以喔，請。那個是抹茶口味的。", tags: ["N5", "敬語"] } ] },
  { category: "購物消費", title: "請店員拿新的商品", icon: "✨", description: "不想拿架上的展示品", dialogues: [ { speaker: "顧客", role: "user", text: "展示品じゃなくて、新しい在庫を出してもらえますか。", furigana: "展[てん]示[じ]品[ひん]じゃなくて、新[あたら]しい在[ざい]庫[こ]を出[だ]してもらえますか。", translation: "我不想拿展示品，可以幫我拿新的庫存嗎？", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "かしこまりました。奥から新しいものをお持ちいたします。", furigana: "かしこまりました。奥[おく]から新[あたら]しいものをお持[も]ちいたします。", translation: "好的。我去後面幫您拿全新的過來。", tags: ["N4", "謙讓語"] } ] },

  // ✈️ 旅遊觀光 - 景點導覽 (10)
  { category: "景點導覽", title: "問路", icon: "🗺️", description: "在街上向當地人問路", dialogues: [ { speaker: "旅客", role: "user", text: "すみません、浅草寺にはどう行けばいいですか。", furigana: "すみません、浅[あさ]草[くさ]寺[でら]にはどう行[い]けばいいですか。", translation: "不好意思，請問要去淺草寺該怎麼走？", tags: ["N5", "敬語", "問路"] }, { speaker: "路人", role: "staff", text: "この道をまっすぐ行って、最初の信号を右に曲がるとすぐですよ。", furigana: "この道[みち]をまっすぐ行[い]って、最[さい]初[しょ]の信[しん]号[ごう]を右[みぎ]に曲[ま]がるとすぐですよ。", translation: "這條路直走，在第一個紅綠燈右轉馬上就到了喔。", tags: ["N4", "敬語"] } ] },
  { category: "景點導覽", title: "購買景點門票", icon: "🎟️", description: "購買不同票種與索取導覽手冊", dialogues: [ { speaker: "旅客", role: "user", text: "大人2枚、子供1枚お願いします。", furigana: "大[おと]人[な]2枚[まい]、子[こ]供[ども]1枚[まい]お願[ねが]いします。", translation: "請給我兩張全票，一張半票。", tags: ["N5", "敬語"] }, { speaker: "售票員", role: "staff", text: "3500円になります。パンフレットはこちらです。", furigana: "3500円[えん]になります。パンフレットはこちらです。", translation: "總共是3500日圓。簡介導覽在這邊。", tags: ["N5", "敬語"] } ] },
  { category: "景點導覽", title: "請求路人協助拍照", icon: "📷", description: "請人幫忙合照與感謝", dialogues: [ { speaker: "旅客", role: "user", text: "すみません、シャッターを押していただけませんか。", furigana: "すみません、シャッターを押[お]していただけませんか。", translation: "不好意思，可以幫我們按個快門拍照嗎？", tags: ["N4", "敬語", "請求"] }, { speaker: "路人", role: "staff", text: "はい、チーズ！もう一枚縦で撮りますね。", furigana: "はい、チーズ！もう一[いち]枚[まい]縦[たて]で撮[と]りますね。", translation: "好，西瓜！我再幫你們直的拍一張喔。", tags: ["N4", "敬語"] } ] },
  { category: "景點導覽", title: "主動幫別人拍照", icon: "📸", description: "看到別人在自拍，主動提議幫忙", dialogues: [ { speaker: "旅客", role: "user", text: "よかったら、写真撮りましょうか。", furigana: "よかったら、写[しゃ]真[しん]撮[と]りましょうか。", translation: "如果不介意的話，我幫你們拍吧？", tags: ["N4", "敬語", "搭話"] }, { speaker: "路人", role: "staff", text: "本当ですか？助かります！お願いします。", furigana: "本[ほん]当[とう]ですか？助[たす]かります！お願[ねが]いします。", translation: "真的嗎？幫了大忙！拜託你了。", tags: ["N5", "敬語"] } ] },
  { category: "景點導覽", title: "詢問營業時間", icon: "⏱️", description: "確認博物館或景點何時關門", dialogues: [ { speaker: "旅客", role: "user", text: "ここは今日の何時まで開いていますか。", furigana: "ここは今[きょう]日[きょう]の何[なん]時[じ]まで開[あ]いていますか。", translation: "請問這裡今天開到幾點？", tags: ["N5", "敬語"] }, { speaker: "館員", role: "staff", text: "午後5時までですが、最終入場は4時半となっております。", furigana: "午[ご]後[ご]5時[じ]までですが、最[さい]終[しゅう]入[にゅう]場[じょう]は4時[じ]半[はん]となっております。", translation: "到下午5點，但最後入場時間是4點半喔。", tags: ["N4", "敬語"] } ] },
  { category: "景點導覽", title: "詢問是否能拍照", icon: "🚫", description: "在寺廟或美術館內確認規定", dialogues: [ { speaker: "旅客", role: "user", text: "この仏像は、写真を撮っても大丈夫ですか。", furigana: "この仏[ぶつ]像[ぞう]は、写[しゃ]真[しん]を撮[と]っても大[だい]丈[じょう]夫[ぶ]ですか。", translation: "這尊佛像可以拍照嗎？", tags: ["N4", "敬語"] }, { speaker: "工作人員", role: "staff", text: "申し訳ありません。館内は撮影禁止となっております。", furigana: "申[もう]し訳[わけ]ありません。館[かん]内[ない]は撮[さつ]影[えい]禁[きん]止[し]となっております。", translation: "非常抱歉。館內是禁止攝影的。", tags: ["N3", "敬語"] } ] },
  { category: "景點導覽", title: "導覽機租借", icon: "🎧", description: "租用語音導覽設備", dialogues: [ { speaker: "旅客", role: "user", text: "日本語以外の音声ガイドはありますか。", furigana: "日[にほん]本[ご]語[ご]以[い]外[がい]の音[おん]声[せい]ガイドはありますか。", translation: "請問有日文以外的語音導覽嗎？", tags: ["N4", "敬語"] }, { speaker: "櫃台", role: "staff", text: "はい、英語と中国語をご用意しております。一台500円です。", furigana: "はい、英[えい]語[ご]と中[ちゅう]国[こく]語[ご]をご用[よう]意[い]しております。一[いち]台[だい]500円[えん]です。", translation: "有的，我們有準備英文和中文。一台500日圓。", tags: ["N4", "謙讓語"] } ] },
  { category: "景點導覽", title: "詢問洗手間位置", icon: "🚻", description: "在廣大的園區內找廁所", dialogues: [ { speaker: "旅客", role: "user", text: "お手洗いはどこかご存知ですか。", furigana: "お手[て]洗[あら]いはどこかご存[ぞん]知[じ]ですか。", translation: "請問您知道洗手間在哪裡嗎？", tags: ["N4", "尊敬語"] }, { speaker: "清潔員", role: "staff", text: "あの角を曲がって、お土産屋さんの裏にありますよ。", furigana: "あの角[かど]を曲[ま]がって、お土[み]産[やげ]屋[や]さんの裏[うら]にありますよ。", translation: "過了那個轉角，在土產店的後面喔。", tags: ["N5", "敬語"] } ] },
  { category: "景點導覽", title: "索取紀念章", icon: "💮", description: "收集車站或景點的印章", dialogues: [ { speaker: "旅客", role: "user", text: "記念スタンプを押したいんですが、どこにありますか。", furigana: "記[き]念[ねん]スタンプを押[お]したいんですが、どこにありますか。", translation: "我想蓋紀念章，請問在哪裡呢？", tags: ["N4", "敬語"] }, { speaker: "站務員", role: "staff", text: "スタンプ台なら、改札を出てすぐ右側に設置しています。", furigana: "スタンプ台[だい]なら、改[かい]札[さつ]を出[で]てすぐ右[みぎ]側[がわ]に設[せっ]置[ち]しています。", translation: "印章台的話，出票閘口後馬上右轉就有設置了。", tags: ["N3", "敬語"] } ] },
  { category: "景點導覽", title: "領取排隊號碼牌", icon: "🎫", description: "熱門景點抽整理券", dialogues: [ { speaker: "旅客", role: "user", text: "今からだと、どれくらい待ちますか。", furigana: "今[いま]からだと、どれくらい待[ま]ちますか。", translation: "現在排隊的話，大概要等多久？", tags: ["N5", "敬語"] }, { speaker: "工作人員", role: "staff", text: "ただいま約60分待ちです。こちらの整理券をお取りください。", furigana: "ただいま約[やく]60分[ぷん]待[ま]ちです。こちらの整[せい]理[り]券[けん]をお取[と]りください。", translation: "目前約需等候60分鐘。請抽取這張號碼牌。", tags: ["N4", "敬語"] } ] },

  // ✈️ 旅遊觀光 - 緊急狀況 (10)
  { category: "緊急狀況", title: "遺失物品", icon: "👜", description: "在車站或警局報失物品", dialogues: [ { speaker: "旅客", role: "user", text: "電車にカバンを置き忘れました。", furigana: "電[でん]車[しゃ]にカバンを置[お]き忘[わす]れました。", translation: "我把包包忘在電車上了。", tags: ["N4", "敬語", "求助"] }, { speaker: "站務員", role: "staff", text: "落ち着いてください。何線の何時頃ですか。", furigana: "落[お]ち着[つ]いてください。何[なに]線[せん]の何[なん]時[じ]頃[ごろ]ですか。", translation: "請冷靜。是哪條路線大約幾點的車？", tags: ["N4", "敬語"] } ] },
  { category: "緊急狀況", title: "迷路求助", icon: "🧭", description: "找不到路或搭錯車", dialogues: [ { speaker: "旅客", role: "user", text: "道に迷ってしまいました。ここは地図のどこですか。", furigana: "道[みち]に迷[まよ]ってしまいました。ここは地[ち]図[ず]のどこですか。", translation: "我迷路了。請問這裡是地圖上的哪裡？", tags: ["N4", "敬語", "求助"] }, { speaker: "路人", role: "staff", text: "今いるのはここです。駅に戻りたいなら、私が案内しますよ。", furigana: "今[いま]いるのはここです。駅[えき]に戻[もど]りたいなら、私[わたし]が案[あん]内[ない]しますよ。", translation: "現在在這裡。如果你想回車站，我帶你去吧。", tags: ["N4", "敬語"] } ] },
  { category: "緊急狀況", title: "突發疾病就醫", icon: "🚑", description: "身體不適與呼叫救護車", dialogues: [ { speaker: "旅客", role: "user", text: "気分がとても悪いです。救急車を呼んでください。", furigana: "気[き]分[ぶん]がとても悪[わる]いです。救[きゅう]急[きゅう]車[しゃ]を呼[よ]んでください。", translation: "我非常不舒服。請幫我叫救護車。", tags: ["N4", "敬語", "求助", "緊急"] }, { speaker: "飯店人員", role: "staff", text: "すぐに手配します！保険証はお持ちですか。", furigana: "すぐに手[て]配[はい]します！保[ほ]険[けん]証[しょう]はお持[も]ちですか。", translation: "我馬上叫！您有帶健保卡或保險證明嗎？", tags: ["N3", "敬語"] } ] },
  { category: "緊急狀況", title: "聯絡大使館或報警", icon: "👮", description: "護照遺失或遭遇竊盜", dialogues: [ { speaker: "旅客", role: "user", text: "パスポートと財布を盗まれました。", furigana: "パスポートと財[さい]布[ふ]を盗[ぬす]まれました。", translation: "我的護照和錢包被偷了。", tags: ["N4", "敬語", "被動語態", "求助"] }, { speaker: "警察", role: "staff", text: "まずは被害届を作成しましょう。それから大使館に連絡してください。", furigana: "まずは被[ひ]害[がい]届[とどけ]を作[さく]成[せい]しましょう。それから大[たい]使[し]館[かん]に連[れん]絡[らく]してください。", translation: "我們先生效報案證明。然後請您聯絡大使館。", tags: ["N3", "敬語"] } ] },
  { category: "緊急狀況", title: "遇到地震避難", icon: "🫨", description: "感受到強烈搖晃時", dialogues: [ { speaker: "飯店人員", role: "staff", text: "地震です！慌てずに机の下に隠れてください！", furigana: "地[じ]震[しん]です！慌[あわ]てずに机[つくえ]の下[した]に隠[かく]れてください！", translation: "地震！請不要慌張，躲到桌子底下！", tags: ["N3", "敬語", "緊急"] }, { speaker: "旅客", role: "user", text: "揺れが収まりました。外に避難した方がいいですか。", furigana: "揺[ゆ]れが収[おさ]まりました。外[そと]に避[ひ]難[なん]した方[ほう]がいいですか。", translation: "搖晃停止了。最好去外面避難嗎？", tags: ["N3", "敬語"] } ] },
  { category: "緊急狀況", title: "提款機吞卡", icon: "💳", description: "信用卡被ATM吃掉", dialogues: [ { speaker: "旅客", role: "user", text: "ATMからクレジットカードが出てきません。", furigana: "ATMからクレジットカードが出[で]てきません。", translation: "信用卡被ATM吃掉，出不來了。", tags: ["N4", "敬語", "求助"] }, { speaker: "銀行員", role: "staff", text: "ご不便をおかけします。機械を開けますので、少しお待ちください。", furigana: "ご不[ふ]便[べん]をおかけします。機[き]械[かい]を開[あ]けますので、少[すこ]しお待[ま]ちください。", translation: "造成您的困擾了。我們現在把機器打開，請稍候。", tags: ["N3", "謙讓語"] } ] },
  { category: "緊急狀況", title: "找尋走失同伴", icon: "👧", description: "在遊樂園或百貨公司走散", dialogues: [ { speaker: "旅客", role: "user", text: "子供とはぐれてしまいました。赤い服を着た5歳の男の子です。", furigana: "子[こ]供[ども]とはぐれてしまいました。赤[あか]い服[ふく]を着[き]た5歳[さい]の男[おとこ]の子[こ]です。", translation: "我和小孩走散了。他穿著紅色衣服，是個5歲的男孩。", tags: ["N3", "敬語", "緊急"] }, { speaker: "服務台", role: "staff", text: "特徴はわかりました。すぐに館内放送をおかけします。", furigana: "特[とく]徴[ちょう]はわかりました。すぐに館[かん]内[ない]放[ほう]送[そう]をおかけします。", translation: "特徵我們記下了。我們馬上為您進行館內廣播。", tags: ["N3", "敬語"] } ] },
  { category: "緊急狀況", title: "被小鋼珠店噪音嚇到", icon: "🙉", description: "進到不熟悉的場所感到不安", dialogues: [ { speaker: "旅客", role: "user", text: "あの、ここはパチンコ店ですか？音が大きすぎて耳が痛いです。", furigana: "あの、ここはパチンコ店[てん]ですか？音[おと]が大[おお]きすぎて耳[みみ]が痛[いた]いです。", translation: "請問這裡是柏青哥店嗎？聲音太大了我耳朵好痛。", tags: ["N4", "敬語"] }, { speaker: "店員", role: "staff", text: "はい、そうです。出口はあちらになりますので、お気をつけて。", furigana: "はい、そうです。出[で]口[ぐち]はあちらになりますので、お気[き]をつけて。", translation: "是的。出口在那邊，請小心慢走。", tags: ["N5", "敬語"] } ] },
  { category: "緊急狀況", title: "被鎖在門外", icon: "🔑", description: "把房卡忘在房間裡", dialogues: [ { speaker: "旅客", role: "user", text: "部屋にカードキーを入れたまま、オートロックが閉まってしまいました。", furigana: "部[へ]屋[や]にカードキーを入[い]れたまま、オートロックが閉[し]まってしまいました。", translation: "我不小心把房卡留在房間裡，結果自動門鎖上了。", tags: ["N3", "敬語", "求助"] }, { speaker: "櫃台", role: "staff", text: "ご本人様確認の後、マスターキーで開錠いたします。", furigana: "ご本[ほん]人[にん]様[さま]確[かく]認[にん]の後[のち]、マスターキーで開[かい]錠[じょう]いたします。", translation: "在確認您的身分後，我們將用萬能鑰匙為您開門。", tags: ["N2", "謙讓語"] } ] },
  { category: "緊急狀況", title: "車禍糾紛", icon: "💥", description: "租車發生擦撞事故", dialogues: [ { speaker: "旅客", role: "user", text: "レンタカーをこすってしまいました。どうすればいいですか。", furigana: "レンタカーをこすってしまいました。どうすればいいですか。", translation: "我不小心擦撞到租來的車了。該怎麼辦？", tags: ["N3", "敬語", "求助"] }, { speaker: "租車公司", role: "staff", text: "怪我はありませんか？まずは警察を呼んで、事故証明をもらってください。", furigana: "怪[け]我[が]はありませんか？まずは警[けい]察[さつ]を呼[よ]んで、事[じ]故[こ]証[しょう]明[めい]をもらってください。", translation: "有人受傷嗎？請先報警，並索取事故證明。", tags: ["N3", "敬語"] } ] }
];

const dbPath = 'c:/ai/jlpt_data_export.json';
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

data.forEach((item, index) => {
  item.id = `conv_travel_mass_${index}`;
  item.stage = "✈️ 旅遊觀光 (Travel & Sightseeing)";
  db.JLPT_DATA.conversations.push(item);
});

fs.writeFileSync(dbPath, JSON.stringify(db, null, 2), 'utf8');
console.log(`Injected ${data.length} Massive Travel scenarios.`);
