const fs = require('fs');

const data = [
  // 🍻 交友休閒 - 興趣與嗜好 (10)
  { category: "興趣與嗜好", title: "分享電影與音樂", icon: "🎬", description: "和朋友討論最近看過的電影", dialogues: [ { speaker: "朋友", role: "staff", text: "最近、何か面白い映画見た？", furigana: "最[さい]近[きん]、何[なに]か面[おも]白[しろ]い映[えい]画[が]見[み]た？", translation: "最近有看什麼有趣的電影嗎？", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "うん、昨日新しいアニメの映画見たよ。映像がすごく綺麗だった！", furigana: "うん、昨[きのう]日[のう]新[あたら]しいアニメの映[えい]画[が]見[み]たよ。映[えい]像[ぞう]がすごく綺[き]麗[れい]だった！", translation: "有啊，昨天看了新的動畫電影。畫面超級美的！", tags: ["N4", "常體"] } ] },
  { category: "興趣與嗜好", title: "交流動漫心得", icon: "🎌", description: "討論新番與喜愛的角色", dialogues: [ { speaker: "主角", role: "user", text: "今期のアニメ、どれか見てる？", furigana: "今[こん]期[き]のアニメ、どれか見[み]てる？", translation: "這季的動畫你有看哪部嗎？", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "もちろん！あの異世界もの、展開が熱くて最高だよね！", furigana: "もちろん！あの異[い]世[せ]界[かい]もの、展[てん]開[かい]が熱[あつ]くて最[さい]高[こう]だよね！", translation: "當然！那部異世界轉生的，劇情超熱血超棒的！", tags: ["N3", "常體", "流行語"] } ] },
  { category: "興趣與嗜好", title: "運動與戶外活動", icon: "⚽", description: "聊聊平時的運動習慣", dialogues: [ { speaker: "朋友", role: "staff", text: "休みの日はいつも何してるの？", furigana: "休[やす]みの日[ひ]はいつも何[なに]してるの？", translation: "放假的時候你都在做什麼？", tags: ["N5", "常體"] }, { speaker: "主角", role: "user", text: "よく友達とフットサルをしてるよ。体を動かすとスッキリするんだ。", furigana: "よく友[とも]達[だち]とフットサルをしてるよ。体[からだ]を動[うご]かすとスッキリするんだ。", translation: "常和朋友去踢五人制足球。動一動身體感覺很清爽。", tags: ["N4", "常體", "男生用語"] } ] },
  { category: "興趣與嗜好", title: "遊戲與休閒", icon: "🎮", description: "討論手遊或主機遊戲", dialogues: [ { speaker: "主角", role: "user", text: "ねえ、そのゲーム、レベル上げ大変じゃない？", furigana: "ねえ、そのゲーム、レベル上[あ]げ大[たい]変[へん]じゃない？", translation: "欸，那款遊戲升級是不是很累人啊？", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "そうなんだよ。ガチャも全然いいの出ないし、最悪。", furigana: "そうなんだよ。ガチャも全[ぜん]然[ぜん]いいの出[で]ないし、最[さい]悪[あく]。", translation: "就是說啊。而且轉蛋也完全抽不到好東西，超慘的。", tags: ["N3", "常體"] } ] },
  { category: "興趣與嗜好", title: "分享愛吃的甜點", icon: "🍰", description: "跟朋友聊喜歡的甜點店", dialogues: [ { speaker: "朋友", role: "staff", text: "駅前に新しいカフェできたの知ってる？ケーキが美味しいらしいよ。", furigana: "駅[えき]前[まえ]に新[あたら]しいカフェできたの知[し]ってる？ケーキが美[おい]味[し]しいらしいよ。", translation: "你知道車站前面新開了一家咖啡廳嗎？聽說蛋糕很好吃喔。", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "え、本当？甘いものには目がないんだよね。今度行ってみようよ！", furigana: "え、本[ほん]当[とう]？甘[あま]いものには目[め]がないんだよね。今[こん]度[ど]行[い]ってみようよ！", translation: "欸，真的嗎？我對甜食最沒有抵抗力了。下次一起去看看吧！", tags: ["N3", "常體", "慣用語"] } ] },
  { category: "興趣與嗜好", title: "交流語言學習", icon: "📚", description: "討論學日文或英文的方法", dialogues: [ { speaker: "主角", role: "user", text: "最近、英語の勉強を始めたんだけど、なかなか上達しなくて。", furigana: "最[さい]近[きん]、英[えい]語[ご]の勉[べん]強[きょう]を始[はじ]めたんだけど、なかなか上[じょう]達[たつ]しなくて。", translation: "最近我開始學英文，但一直沒有進步。", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "洋楽を聴いたり、海外ドラマを見たりするのがおすすめだよ！", furigana: "洋[よう]楽[がく]を聴[き]いたり、海[かい]外[がい]ドラマを見[み]たりするのがおすすめだよ！", translation: "推薦你可以聽聽西洋音樂，或是看看海外影集喔！", tags: ["N4", "常體"] } ] },
  { category: "興趣與嗜好", title: "討論偶像與追星", icon: "🎤", description: "聊喜歡的偶像團體", dialogues: [ { speaker: "朋友", role: "staff", text: "昨日の歌番組、推しが出てたからリアタイしちゃった！", furigana: "昨[きのう]日[のう]の歌[うた]番[ばん]組[ぐみ]、推[お]しが出[で]てたからリアタイしちゃった！", translation: "昨天的歌唱節目，因為有我的偶像(推)出來，我就看了直播(Real-time)！", tags: ["N3", "常體", "流行語"] }, { speaker: "主角", role: "user", text: "マジで！？見逃したー！あとで見逃し配信探してみる。", furigana: "マジで！？見[み]逃[のが]したー！あとで見[み]逃[のが]し配[はい]信[しん]探[さが]してみる。", translation: "真的假的！？我錯過了！我等一下找找看重播。", tags: ["N3", "常體", "網路用語"] } ] },
  { category: "興趣與嗜好", title: "攝影與拍照", icon: "📸", description: "聊買相機或拍照技巧", dialogues: [ { speaker: "主角", role: "user", text: "そのカメラ、かっこいいね！どこのメーカー？", furigana: "そのカメラ、かっこいいね！どこのメーカー？", translation: "那台相機很帥耶！是哪一家的？", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "これ？最近買ったミラーレスなんだ。ボケ感がすごくいいんだよ。", furigana: "これ？最[さい]近[きん]買[か]ったミラーレスなんだ。ボケ感[かん]がすごくいいんだよ。", translation: "這個嗎？是我最近買的無反相機。它的散景效果非常好喔。", tags: ["N3", "常體"] } ] },
  { category: "興趣與嗜好", title: "做菜與食譜", icon: "🍳", description: "分享自己最近做的料理", dialogues: [ { speaker: "朋友", role: "staff", text: "最近、自炊にハマっててさ。昨日初めて肉じゃが作ったんだ。", furigana: "最[さい]近[きん]、自[じ]炊[すい]にハマっててさ。昨[きのう]日[のう]初[はじ]めて肉[にく]じゃが作[つく]ったんだ。", translation: "最近我迷上了自己煮飯。昨天第一次做了馬鈴薯燉肉。", tags: ["N3", "常體"] }, { speaker: "主角", role: "user", text: "すごいじゃん！今度私にも作ってよー。", furigana: "すごいじゃん！今[こん]度[ど]私[わたし]にも作[つく]ってよー。", translation: "很厲害嘛！下次也做給我吃嘛～。", tags: ["N4", "常體"] } ] },
  { category: "興趣與嗜好", title: "聊旅遊回憶", icon: "✈️", description: "分享去哪裡玩的趣事", dialogues: [ { speaker: "主角", role: "user", text: "先週、京都に行ってきたんだけど、紅葉がすっごく綺麗だったよ！", furigana: "先[せん]週[しゅう]、京[きょう]都[と]に行[い]ってきたんだけど、紅[こう]葉[よう]がすっごく綺[き]麗[れい]だったよ！", translation: "我上禮拜去了京都，楓葉超級漂亮的喔！", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "いいなー！私も秋の京都、ずっと行きたいと思ってるんだよね。", furigana: "いいなー！私[わたし]も秋[あき]の京[きょう]都[と]、ずっと行[い]きたいと思[おも]ってるんだよね。", translation: "真好啊！我也一直很想去秋天的京都看看呢。", tags: ["N4", "常體"] } ] },

  // 🍻 交友休閒 - 邀約與安排 (10)
  { category: "邀約與安排", title: "提議聚餐", icon: "🍽️", description: "問朋友要不要一起去吃飯", dialogues: [ { speaker: "主角", role: "user", text: "今度の金曜日の夜、時間ある？一緒にご飯でもどう？", furigana: "今[こん]度[ど]の金[きん]曜[よう]日[び]の夜[よる]、時[じ]間[かん]ある？一[いっ]緒[しょ]にご飯[はん]でもどう？", translation: "這禮拜五晚上你有空嗎？要不要一起去吃個飯？", tags: ["N5", "常體", "邀約"] }, { speaker: "朋友", role: "staff", text: "金曜なら空いてるよ！どこ行く？", furigana: "金[きん]曜[よう]なら空[あ]いてるよ！どこ行[い]く？", translation: "禮拜五的話我有空喔！要去哪裡？", tags: ["N5", "常體"] } ] },
  { category: "邀約與安排", title: "約看電影", icon: "🎟️", description: "約朋友週末去看新上映的電影", dialogues: [ { speaker: "主角", role: "user", text: "話題のあの映画、今週末見に行かない？", furigana: "話[わ]題[だい]のあの映[えい]画[が]、今[こん]週[しゅう]末[まつ]見[み]に行[い]かない？", translation: "那部很有話題的電影，這週末要不要去看？", tags: ["N4", "常體", "邀約"] }, { speaker: "朋友", role: "staff", text: "いいね！行きたいと思ってたんだ。私がチケット予約しとくよ。", furigana: "いいね！行[い]きたいと思[おも]ってたんだ。私[わたし]がチケット予[よ]約[やく]しとくよ。", translation: "好啊！我本來就想去看了。我先去訂票喔。", tags: ["N4", "常體", "女生用語"] } ] },
  { category: "邀約與安排", title: "確認雙方時間", icon: "📅", description: "確認見面的時間地點", dialogues: [ { speaker: "朋友", role: "staff", text: "明日の待ち合わせ、何時にする？", furigana: "明[あした]日[た]の待[ま]ち合[あ]わせ、何[なん]時[じ]にする？", translation: "明天約見面，要約幾點？", tags: ["N5", "常體"] }, { speaker: "主角", role: "user", text: "1時に渋谷のハチ公前でどう？", furigana: "1時[じ]に渋[しぶ]谷[や]のハチ公[こう]前[まえ]でどう？", translation: "約1點在澀谷八公像前面如何？", tags: ["N5", "常體"] } ] },
  { category: "邀約與安排", title: "規劃週末出遊", icon: "🏞️", description: "討論要去海邊還是山上", dialogues: [ { speaker: "主角", role: "user", text: "連休、どっか遠出しない？海とか。", furigana: "連[れん]休[きゅう]、どっか遠[とお]出[で]しない？海[うみ]とか。", translation: "連假要不要去遠一點的地方？像是海邊之類的。", tags: ["N4", "常體", "邀約"] }, { speaker: "朋友", role: "staff", text: "海もいいけど、まだ水冷たくない？温泉の方がよくない？", furigana: "海[うみ]もいいけど、まだ水[みず]冷[つめ]たくない？温[おん]泉[せん]の方[ほう]がよくない？", translation: "海邊也不錯，但水不會還很冷嗎？去泡溫泉不是比較好？", tags: ["N3", "常體"] } ] },
  { category: "邀約與安排", title: "約定見面地點", icon: "📍", description: "怕迷路所以約在好找的地方", dialogues: [ { speaker: "主角", role: "user", text: "新宿駅は迷いそうだから、東口の交番前で待ち合わせにしない？", furigana: "新[しん]宿[じゅく]駅[えき]は迷[まよ]いそうだから、東[ひがし]口[ぐち]の交[こう]番[ばん]前[まえ]で待[ま]ち合[あ]わせにしない？", translation: "新宿車站很容易迷路，我們約在東口的派出所前面好嗎？", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "オッケー、わかった。着いたらLINEするね。", furigana: "オッケー、わかった。着[つ]いたらLINEするね。", translation: "OK，沒問題。我到了再傳LINE給你。", tags: ["N5", "常體"] } ] },
  { category: "邀約與安排", title: "遲到的報備", icon: "🏃", description: "快遲到了趕緊通知朋友", dialogues: [ { speaker: "主角", role: "user", text: "ごめん！電車が遅れてて、10分くらい遅刻しそう！", furigana: "ごめん！電[でん]車[しゃ]が遅[おく]れてて、10分[ぷん]くらい遅[ち]刻[こく]しそう！", translation: "抱歉！電車誤點了，我大概會遲到10分鐘！", tags: ["N4", "常體", "緊急"] }, { speaker: "朋友", role: "staff", text: "了解！近くのカフェで待ってるから、焦らなくていいよー。", furigana: "了[りょう]解[かい]！近[ちか]くのカフェで待[ま]ってるから、焦[あせ]らなくていいよー。", translation: "了解！我在附近的咖啡廳等你，不用急喔～", tags: ["N4", "常體"] } ] },
  { category: "邀約與安排", title: "臨時取消約會", icon: "🙏", description: "突然生病或有急事", dialogues: [ { speaker: "主角", role: "user", text: "本当にごめん、急に熱が出ちゃって…今日の約束、キャンセルしてもいい？", furigana: "本[ほん]当[とう]にごめん、急[きゅう]に熱[ねつ]が出[で]ちゃって…今[きょう]日[きょう]の約[やく]束[そく]、キャンセルしてもいい？", translation: "真的非常抱歉，我突然發燒了...今天的約會可以取消嗎？", tags: ["N3", "常體", "抱歉"] }, { speaker: "朋友", role: "staff", text: "え！大丈夫？もちろん気にしないで。ゆっくり休んでね！", furigana: "え！大[だい]丈[じょう]夫[ぶ]？もちろん気[き]にしないで。ゆっくり休[やす]んでね！", translation: "欸！你還好嗎？當然沒問題別在意。好好休息喔！", tags: ["N4", "常體"] } ] },
  { category: "邀約與安排", title: "詢問有無忌口", icon: "🚫", description: "決定餐廳前問朋友不吃什麼", dialogues: [ { speaker: "主角", role: "user", text: "お店予約するけど、何か食べられないものとかある？", furigana: "お店[みせ]予[よ]約[やく]するけど、何[なに]か食[た]べられないものとかある？", translation: "我要來預約餐廳了，你有什麼不吃的東西嗎？", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "辛いものがちょっと苦手かな。それ以外なら何でもいいよ！", furigana: "辛[から]いものがちょっと苦[にが]手[て]かな。それ以[い]外[がい]なら何[なん]でもいいよ！", translation: "我比較不敢吃辣。除了那個之外什麼都可以喔！", tags: ["N4", "常體"] } ] },
  { category: "邀約與安排", title: "邀約去家裡玩", icon: "🏠", description: "邀請朋友來家裡喝酒打電動", dialogues: [ { speaker: "主角", role: "user", text: "今週末、うちで宅飲みしない？ゲームも買ったし！", furigana: "今[こん]週[しゅう]末[まつ]、うちで宅[たく]飲[の]みしない？ゲームも買[か]ったし！", translation: "這週末要不要來我家喝酒？我也買了新遊戲喔！", tags: ["N4", "常體", "流行語"] }, { speaker: "朋友", role: "staff", text: "行く行く！お酒とおつまみ、適当に買っていくね。", furigana: "行[い]く行[い]く！お酒[さけ]とおつまみ、適[てき]当[とう]に買[か]っていくね。", translation: "去去去！我會隨便買點酒跟下酒菜過去喔。", tags: ["N4", "常體"] } ] },
  { category: "邀約與安排", title: "約會後的道別", icon: "👋", description: "結束一天的行程，約好下次再見", dialogues: [ { speaker: "朋友", role: "staff", text: "今日はすごく楽しかったよ。ありがとう！", furigana: "今[きょう]日[きょう]はすごく楽[たの]しかったよ。ありがとう！", translation: "今天玩得非常開心。謝謝你！", tags: ["N5", "常體"] }, { speaker: "主角", role: "user", text: "こちらこそ！また近いうちに遊ぼうね。気をつけて帰ってね。", furigana: "こちらこそ！また近[ちか]いうちに遊[あそ]ぼうね。気[き]をつけて帰[かえ]ってね。", translation: "我才是！近期內再一起玩吧。回家路上小心喔。", tags: ["N4", "常體"] } ] },

  // 🍻 交友休閒 - 聚餐與派對 (10)
  { category: "聚餐與派對", title: "居酒屋點酒與乾杯", icon: "🍻", description: "第一杯先點生啤酒", dialogues: [ { speaker: "主角", role: "user", text: "とりあえず生でいい？", furigana: "とりあえず生[なま]でいい？", translation: "總之先來杯生啤酒可以嗎？", tags: ["N4", "常體", "居酒屋"] }, { speaker: "朋友", role: "staff", text: "うん、それで。じゃあ、お疲れ様！乾杯！", furigana: "うん、それで。じゃあ、お疲[つか]れ様[さま]！乾[かん]杯[ぱい]！", translation: "嗯，就那個。那麼，辛苦啦！乾杯！", tags: ["N5", "常體"] } ] },
  { category: "聚餐與派對", title: "分攤費用", icon: "💴", description: "吃完飯大家一起分錢 (割り勘)", dialogues: [ { speaker: "主角", role: "user", text: "今日のお会計、割り勘にしようか。一人いくら？", furigana: "今[きょう]日[きょう]のお会[かい]計[けい]、割[わ]り勘[かん]にしようか。一[ひと]人[り]いくら？", translation: "今天的帳單我們各付各的吧。一個人多少錢？", tags: ["N4", "常體", "AA制"] }, { speaker: "朋友", role: "staff", text: "全部で8000円だから、一人4000円だね。はい、細かいのあるよ。", furigana: "全[ぜん]部[ぶ]で8000円[えん]だから、一[ひと]人[り]4000円[えん]だね。はい、細[こま]かいのあるよ。", translation: "總共8000日圓，所以一個人4000日圓。給，我有零錢喔。", tags: ["N4", "常體"] } ] },
  { category: "聚餐與派對", title: "慶祝生日", icon: "🎂", description: "給朋友一個驚喜的生日派對", dialogues: [ { speaker: "主角", role: "user", text: "ハッピーバースデー！これ、みんなからのプレゼント！", furigana: "ハッピーバースデー！これ、みんなからのプレゼント！", translation: "生日快樂！這個是大家送你的禮物！", tags: ["N5", "常體"] }, { speaker: "朋友", role: "staff", text: "えー！びっくりした！本当にありがとう、嬉しい！", furigana: "えー！びっくりした！本[ほん]当[とう]にありがとう、嬉[うれ]しい！", translation: "欸！嚇我一跳！真的謝謝你們，好開心！", tags: ["N4", "常體"] } ] },
  { category: "聚餐與派對", title: "詢問還要不要吃", icon: "🍗", description: "盤子裡剩下最後一塊唐揚雞", dialogues: [ { speaker: "主角", role: "user", text: "この唐揚げ、最後の一個、誰か食べる？", furigana: "この唐[から]揚[あ]げ、最[さい]後[ご]の一[いっ]個[こ]、誰[だれ]か食[た]べる？", translation: "這塊唐揚雞剩下最後一個了，有人要吃嗎？", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "私はもうお腹いっぱいだから、食べていいよ！", furigana: "私[わたし]はもうお腹[なか]いっぱいだから、食[た]べていいよ！", translation: "我已經吃飽了，你吃吧！", tags: ["N4", "常體"] } ] },
  { category: "聚餐與派對", title: "勸酒與拒絕", icon: "🍶", description: "被朋友勸酒但不想喝", dialogues: [ { speaker: "朋友", role: "staff", text: "まだまだ夜は長いよ！もう一杯どう？", furigana: "まだまだ夜[よる]は長[なが]いよ！もう一[いっ]杯[ぱい]どう？", translation: "夜還很長呢！要不要再來一杯？", tags: ["N5", "常體"] }, { speaker: "主角", role: "user", text: "ごめん、私お酒弱いから、次はウーロン茶にしとく。", furigana: "ごめん、私[わたし]お酒[さけ]弱[よわ]いから、次[つぎ]はウーロン茶[ちゃ]にしとく。", translation: "抱歉，我不勝酒力，下一杯我喝烏龍茶就好。", tags: ["N4", "常體", "拒絕"] } ] },
  { category: "聚餐與派對", title: "吃不下要打包", icon: "🥡", description: "在朋友家聚餐食物剩很多", dialogues: [ { speaker: "朋友", role: "staff", text: "ピザ、けっこう余っちゃったね。どうする？", furigana: "ピザ、けっこう余[あま]っちゃったね。どうする？", translation: "披薩剩蠻多的耶。怎麼辦？", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "もったいないから、タッパーに入れて持ち帰ってもいい？明日の朝ごはんにする！", furigana: "もったいないから、タッパーに入[い]れて持[も]ち帰[かえ]ってもいい？明[あした]日[た]の朝[あさ]ごはんにする！", translation: "太浪費了，我可以裝進保鮮盒帶回去嗎？當明天的早餐！", tags: ["N4", "常體"] } ] },
  { category: "聚餐與派對", title: "推薦好吃的菜", icon: "🤤", description: "吃到好吃的東西分享給朋友", dialogues: [ { speaker: "主角", role: "user", text: "これ、めちゃくちゃ美味しいよ！一口食べてみなよ。", furigana: "これ、めちゃくちゃ美[おい]味[し]しいよ！一[ひと]口[くち]食[た]べてみなよ。", translation: "這個超級好吃的喔！你吃一口看看啦。", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "え、ホント？…うわ、マジだ！とろける！", furigana: "え、ホント？…うわ、マジだ！とろける！", translation: "欸，真的嗎？...哇，真的耶！入口即化！", tags: ["N5", "常體", "流行語"] } ] },
  { category: "聚餐與派對", title: "結帳時幫忙先墊錢", icon: "💰", description: "朋友沒帶零錢，幫忙先付", dialogues: [ { speaker: "朋友", role: "staff", text: "あ、ごめん、1万円札しかないや。細かいのある？", furigana: "あ、ごめん、1万[まん]円[えん]札[さつ]しかないや。細[こま]かいのある？", translation: "啊，抱歉，我只有一萬圓大鈔。你有零錢嗎？", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "じゃあ、ここは私がまとめて払っておくよ。あとでPayPayで送って！", furigana: "じゃあ、ここは私[わたし]がまとめて払[はら]っておくよ。あとでPayPayで送[おく]って！", translation: "那這裡我先一起付吧。你晚點再用PayPay轉給我就好！", tags: ["N3", "常體", "行動支付"] } ] },
  { category: "聚餐與派對", title: "KTV點歌", icon: "🎤", description: "在包廂裡互相點歌", dialogues: [ { speaker: "主角", role: "user", text: "次、何歌う？私がリモコンで入れとくよ。", furigana: "次[つぎ]、何[なに]歌[うた]う？私[わたし]がリモコンで入[い]れとくよ。", translation: "接下來你要唱什麼？我用遙控器幫你點。", tags: ["N5", "常體"] }, { speaker: "朋友", role: "staff", text: "じゃあ、最近流行ってるあの曲お願い！サビしか知らないけど（笑）", furigana: "じゃあ、最[さい]近[きん]流[はや]ってるあの曲[きょく]お願[ねが]い！サビしか知[し]らないけど（笑[わらい]）", translation: "那就幫我點最近很流行的那首歌！雖然我只會唱副歌(笑)", tags: ["N4", "常體"] } ] },
  { category: "聚餐與派對", title: "喝醉了", icon: "😵‍💫", description: "朋友喝太多了需要照顧", dialogues: [ { speaker: "主角", role: "user", text: "ちょっと飲みすぎじゃない？お水飲んだ方がいいよ。", furigana: "ちょっと飲[の]みすぎじゃない？お水[みず]飲[の]んだ方[ほう]がいいよ。", translation: "你是不是喝太多了？喝點水比較好喔。", tags: ["N4", "常體", "關心"] }, { speaker: "朋友", role: "staff", text: "大丈夫大丈夫～！もう一件行こうよ～！", furigana: "大[だい]丈[じょう]夫[ぶ]大[だい]丈[じょう]夫[ぶ]～！もう一[いっ]件[けん]行[い]こうよ～！", translation: "沒事沒事～！我們再去續攤啦～！", tags: ["N5", "常體", "醉漢"] } ] },

  // 🍻 交友休閒 - 情感交流 (10)
  { category: "情感交流", title: "表達關心", icon: "❤️", description: "發現朋友不對勁時的關心", dialogues: [ { speaker: "主角", role: "user", text: "なんか今日元気なくない？どうしたの？", furigana: "なんか今[きょう]日[きょう]元[げん]気[き]なくない？どうしたの？", translation: "你今天怎麼好像沒什麼精神？怎麼了？", tags: ["N4", "常體", "關心"] }, { speaker: "朋友", role: "staff", text: "実は、昨日彼女と別れちゃって…。ちょっと落ち込んでるんだ。", furigana: "実[じつ]は、昨[きのう]日[のう]彼[かの]女[じょ]と別[わか]れちゃって…。ちょっと落[お]ち込[こ]んでるんだ。", translation: "其實，我昨天跟女朋友分手了... 覺得有點沮喪。", tags: ["N3", "常體", "男生用語"] } ] },
  { category: "情感交流", title: "傾聽朋友的煩惱", icon: "👂", description: "聆聽並給予簡單的回應", dialogues: [ { speaker: "朋友", role: "staff", text: "最近仕事が忙しすぎて、全然自分の時間が持てないんだよね。", furigana: "最[さい]近[きん]仕[し]事[ごと]が忙[いそが]しすぎて、全[ぜん]然[ぜん]自[じ]分[ぶん]の時[じ]間[かん]が持[も]てないんだよね。", translation: "最近工作太忙了，完全沒有自己的時間。", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "そっか、それは辛いね。あまり無理しないでね。", furigana: "そっか、それは辛[つら]いね。あまり無[む]理[り]しないでね。", translation: "這樣啊，那真的很辛苦呢。別太勉強自己了喔。", tags: ["N4", "常體", "安慰"] } ] },
  { category: "情感交流", title: "給予鼓勵與建議", icon: "💪", description: "朋友要面試前的加油打氣", dialogues: [ { speaker: "朋友", role: "staff", text: "明日、ついに第一志望の面接なんだ。すごく緊張する。", furigana: "明[あした]日[た]、ついに第[だい]一[いち]志[し]望[ぼう]の面[めん]接[せつ]なんだ。すごく緊[きん]張[ちょう]する。", translation: "明天終於是第一志願的面試了。我好緊張。", tags: ["N3", "常體"] }, { speaker: "主角", role: "user", text: "大丈夫だよ！今まであんなに頑張ってきたんだから。自信持って！", furigana: "大[だい]丈[じょう]夫[ぶ]だよ！今[いま]まであんなに頑[がん]張[ば]ってきたんだから。自[じ]信[しん]持[も]って！", translation: "沒問題的啦！你一直以來都這麼努力了。要對自己有信心！", tags: ["N4", "常體", "鼓勵"] } ] },
  { category: "情感交流", title: "幫朋友出主意", icon: "💡", description: "朋友不知道該挑哪個禮物", dialogues: [ { speaker: "朋友", role: "staff", text: "彼氏へのプレゼント、時計と財布、どっちがいいと思う？", furigana: "彼[かれ]氏[し]へのプレゼント、時[と]計[けい]と財[さい]布[ふ]、どっちがいいと思[おも]う？", translation: "送給男友的禮物，手錶跟錢包，你覺得哪個好？", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "うーん、財布の方が毎日使うし、実用的でいいんじゃない？", furigana: "うーん、財[さい]布[ふ]の方[ほう]が毎[まい]日[にち]使[つか]うし、実[じつ]用[よう]的[てき]でいいんじゃない？", translation: "嗯～錢包每天都會用到，比較實用，不是蠻好的嗎？", tags: ["N4", "常體", "建議"] } ] },
  { category: "情感交流", title: "八卦與秘密分享", icon: "🤫", description: "偷偷聊別人的八卦", dialogues: [ { speaker: "主角", role: "user", text: "ねえ、ここだけの話なんだけど…山田さんと鈴木さん、付き合ってるらしいよ。", furigana: "ねえ、ここだけの話[はなし]なんだけど…山[やま]田[だ]さんと鈴[すず]木[き]さん、付[つ]き合[あ]ってるらしいよ。", translation: "欸，我只在這裡跟你說喔...聽說山田跟鈴木在交往耶。", tags: ["N3", "常體", "秘密"] }, { speaker: "朋友", role: "staff", text: "えー！ウソ！全然気づかなかった。誰から聞いたの？", furigana: "えー！ウソ！全[ぜん]然[ぜん]気[き]づかなかった。誰[だれ]から聞[き]いたの？", translation: "欸ー！騙人！我完全沒發現。你聽誰說的？", tags: ["N4", "常體"] } ] },
  { category: "情感交流", title: "爭吵後的道歉", icon: "🙇", description: "昨天跟朋友吵架，今天道歉", dialogues: [ { speaker: "主角", role: "user", text: "昨日はキツい言い方してごめんね。ちょっとイライラしてて。", furigana: "昨[きのう]日[のう]はキツい言[い]い方[かた]してごめんね。ちょっとイライラしてて。", translation: "昨天講話太重了對不起。我那時有點煩躁。", tags: ["N3", "常體", "道歉"] }, { speaker: "朋友", role: "staff", text: "ううん、私も意地張ってごめん。もう気にしないで。", furigana: "ううん、私[わたし]も意[い]地[じ]張[は]ってごめん。もう気[き]にしないで。", translation: "不會啦，我也很固執對不起。別放在心上了。", tags: ["N3", "常體"] } ] },
  { category: "情感交流", title: "感謝朋友幫忙", icon: "🙏", description: "朋友幫了個大忙表達感謝", dialogues: [ { speaker: "主角", role: "user", text: "引っ越しの手伝い、本当に助かった！ありがとう！", furigana: "引[ひ]っ越[こ]しの手[て]伝[つだ]い、本[ほん]当[とう]に助[たす]かった！ありがとう！", translation: "搬家來幫忙，真的幫了大忙！謝謝你！", tags: ["N4", "常體", "感謝"] }, { speaker: "朋友", role: "staff", text: "気にしないで！困った時はお互い様だからさ。", furigana: "気[き]にしないで！困[こま]った時[とき]はお互[たが]い様[さま]だからさ。", translation: "別在意！遇到困難本來就是要互相幫忙的嘛。", tags: ["N3", "常體"] } ] },
  { category: "情感交流", title: "聽朋友抱怨", icon: "😤", description: "朋友在抱怨上司", dialogues: [ { speaker: "朋友", role: "staff", text: "うちの課長、言うことがコロコロ変わるから本当にイライラする！", furigana: "うちの課[か]長[ちょう]、言[い]うことがコロコロ変[か]わるから本[ほん]当[とう]にイライラする！", translation: "我們課長講話變來變去，真的讓人很火大！", tags: ["N3", "常體"] }, { speaker: "主角", role: "user", text: "わかるー！それ、めちゃくちゃストレス溜まるよね。", furigana: "わかるー！それ、めちゃくちゃストレス溜[た]まるよね。", translation: "我懂ー！那超級累積壓力的對吧。", tags: ["N3", "常體", "同理心"] } ] },
  { category: "情感交流", title: "表達驚訝", icon: "😲", description: "聽到朋友要結婚的消息", dialogues: [ { speaker: "朋友", role: "staff", text: "実は私、来月結婚することになったんだ。", furigana: "実[じつ]は私[わたし]、来[らい]月[げつ]結[けっこん]婚[こん]することになったんだ。", translation: "其實我，下個月要結婚了。", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "えーっ！本当に！？おめでとう！全然知らなかった！", furigana: "えーっ！本[ほん]当[とう]に！？おめでとう！全[ぜん]然[ぜん]知[し]らなかった！", translation: "欸ー！真的假的！？恭喜你！我完全不知道耶！", tags: ["N5", "常體", "驚訝"] } ] },
  { category: "情感交流", title: "參加婚禮的祝福語", icon: "💒", description: "對新人說的話", dialogues: [ { speaker: "主角", role: "user", text: "ご結婚おめでとうございます。末永くお幸せに！", furigana: "ご結[けっこん]婚[こん]おめでとうございます。末[すえ]長[なが]くお幸[しあわ]せに！", translation: "恭喜你們結婚。祝你們永浴愛河（永遠幸福）！", tags: ["N3", "敬語", "正式祝福"] }, { speaker: "朋友", role: "staff", text: "ありがとう！今日は来てくれて本当に嬉しいよ。", furigana: "ありがとう！今[きょう]日[きょう]は来[き]てくれて本[ほん]当[とう]に嬉[うれ]しいよ。", translation: "謝謝！你今天能來我真的很高興。", tags: ["N4", "常體"] } ] },

  // 🍻 交友休閒 - 意見與態度 (10)
  { category: "意見與態度", title: "委婉拒絕邀約", icon: "🙅", description: "不傷感情的拒絕方式", dialogues: [ { speaker: "朋友", role: "staff", text: "今夜、みんなでカラオケ行くんだけど、一緒に来ない？", furigana: "今[こん]夜[や]、みんなでカラオケ行[い]くんだけど、一[いっ]緒[しょ]に来[こ]ない？", translation: "今晚大家要去唱KTV，你要不要一起來？", tags: ["N5", "常體"] }, { speaker: "主角", role: "user", text: "ごめん！行きたいのは山々なんだけど、明日早いから今日はやめとく。", furigana: "ごめん！行[い]きたいのは山々[やまやま]なんだけど、明[あした]日[た]早[はや]いから今[きょう]日[きょう]はやめとく。", translation: "抱歉！我雖然很想去，但明天要早起，今天就先不去了。", tags: ["N3", "常體", "拒絕"] } ] },
  { category: "意見與態度", title: "表達贊同", icon: "👍", description: "完全同意對方的看法", dialogues: [ { speaker: "朋友", role: "staff", text: "この店のケーキ、甘すぎなくてすごく美味しいよね。", furigana: "この店[みせ]のケーキ、甘[あま]すぎなくてすごく美[おい]味[し]しいよね。", translation: "這家店的蛋糕不會太甜，非常的好吃對吧。", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "ほんとそれ！いくらでも食べられそう。", furigana: "ほんとそれ！いくらでも食[た]べられそう。", translation: "真的就是這樣！感覺吃多少都吃得下。", tags: ["N3", "常體", "流行語"] } ] },
  { category: "意見與態度", title: "提出不同看法", icon: "🤔", description: "委婉表達自己不同意", dialogues: [ { speaker: "朋友", role: "staff", text: "彼は絶対わざとあんなこと言ったんだよ！", furigana: "彼[かれ]は絶[ぜっ]対[たい]わざとあんなこと言[い]ったんだよ！", translation: "他絕對是故意那樣說的啦！", tags: ["N3", "常體"] }, { speaker: "主角", role: "user", text: "うーん、そうかな？悪気はなかったんじゃない？", furigana: "うーん、そうかな？悪[わる]気[ぎ]はなかったんじゃない？", translation: "嗯～是這樣嗎？他應該是沒有惡意的吧？", tags: ["N3", "常體", "反駁"] } ] },
  { category: "意見與態度", title: "坦白說出缺點", icon: "😬", description: "朋友問衣服好不好看", dialogues: [ { speaker: "朋友", role: "staff", text: "この服、どうかな？私に似合ってる？", furigana: "この服[ふく]、どうかな？私[わたし]に似[に]合[あ]ってる？", translation: "這件衣服怎麼樣？適合我嗎？", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "悪くはないけど、さっきの青い方が顔色が明るく見えたよ。", furigana: "悪[わる]くはないけど、さっきの青[あお]い方[ほう]が顔[かお]色[いろ]が明[あか]るく見[み]えたよ。", translation: "是不差啦，但剛剛那件藍色的看起來氣色比較好喔。", tags: ["N3", "常體"] } ] },
  { category: "意見與態度", title: "敷衍與附和", icon: "😶", description: "對話題沒興趣只好敷衍", dialogues: [ { speaker: "朋友", role: "staff", text: "それでね、うちの犬がまた壁を引っ掻いてさー、大変だったの！", furigana: "それでね、うちの犬[いぬ]がまた壁[かべ]を引[ひ]っ掻[か]いてさー、大[たい]変[へん]だったの！", translation: "然後啊，我家的狗又去抓牆壁，超級傷腦筋的！", tags: ["N3", "常體"] }, { speaker: "主角", role: "user", text: "へえー、そうなんだ。それは大変だったね。", furigana: "へえー、そうなんだ。それは大[たい]変[へん]だったね。", translation: "喔ー，這樣啊。那還真是辛苦耶。", tags: ["N5", "常體", "敷衍"] } ] },
  { category: "意見與態度", title: "表達猶豫", icon: "🤷", description: "無法立刻下決定", dialogues: [ { speaker: "朋友", role: "staff", text: "夏休み、ハワイとグアム、どっちに行きたい？", furigana: "夏[なつ]休[やす]み、ハワイとグアム、どっちに行[い]きたい？", translation: "暑假你想去夏威夷還是關島？", tags: ["N5", "常體"] }, { speaker: "主角", role: "user", text: "どっちも魅力的だから迷うなぁ。ちょっと考えさせて。", furigana: "どっちも魅[み]力[りょく]的[てき]だから迷[まよ]うなぁ。ちょっと考[かんが]えさせて。", translation: "兩個都很吸引人，好猶豫喔。讓我考慮一下。", tags: ["N3", "常體"] } ] },
  { category: "意見與態度", title: "承認錯誤", icon: "😥", description: "發現自己搞錯了", dialogues: [ { speaker: "主角", role: "user", text: "あ、ごめん！待ち合わせ、明日じゃなくて今日だったね。勘違いしてた！", furigana: "あ、ごめん！待[ま]ち合[あ]わせ、明[あした]日[た]じゃなくて今[きょう]日[きょう]だったね。勘[かん]違[ちが]いしてた！", translation: "啊，抱歉！約見面是今天不是明天對吧。我搞錯了！", tags: ["N3", "常體"] }, { speaker: "朋友", role: "staff", text: "やっぱり！なんか連絡来ないから、そうじゃないかと思ってた。", furigana: "やっぱり！なんか連[れん]絡[らく]来[こ]ないから、そうじゃないかと思[おも]ってた。", translation: "果然！因為你一直沒聯絡，我就想說是不是這樣。", tags: ["N3", "常體"] } ] },
  { category: "意見與態度", title: "表達不滿", icon: "😠", description: "受不了對方的遲到", dialogues: [ { speaker: "主角", role: "user", text: "もう30分も待ってるんだけど。いつも遅刻するの、いい加減にしてよ！", furigana: "もう30分[ぷん]も待[ま]ってるんだけど。いつも遅[ち]刻[こく]するの、いい加[か]減[げん]にしてよ！", translation: "我已經等了30分鐘了。你每次都遲到，差不多一點好嗎！", tags: ["N3", "常體", "生氣"] }, { speaker: "朋友", role: "staff", text: "本当にごめん！目覚ましが鳴らなくて…怒るのも無理ないよね。", furigana: "本[ほん]当[とう]にごめん！目[め]覚[ざ]ましが鳴[な]らなくて…怒[おこ]るのも無[む]理[り]ないよね。", translation: "真的非常抱歉！鬧鐘沒響...你生氣也是理所當然的。", tags: ["N3", "常體"] } ] },
  { category: "意見與態度", title: "催促對方", icon: "⏰", description: "催朋友快一點出門", dialogues: [ { speaker: "主角", role: "user", text: "ねえ、まだ準備終わらないの？電車行っちゃうよ！", furigana: "ねえ、まだ準[じゅん]備[び]終[お]わらないの？電[でん]車[しゃ]行[い]っちゃうよ！", translation: "欸，你還沒準備好嗎？電車要開走了啦！", tags: ["N4", "常體", "催促"] }, { speaker: "朋友", role: "staff", text: "あと5分！今メイク終わったから、すぐ行く！", furigana: "あと5分[ふん]！今[いま]メイク終[お]わったから、すぐ行[い]く！", translation: "再5分鐘！我現在化好妝了，馬上好！", tags: ["N5", "常體"] } ] },
  { category: "意見與態度", title: "表達無奈", icon: "😮‍💨", description: "遇到倒楣的事只能嘆氣", dialogues: [ { speaker: "主角", role: "user", text: "せっかく洗車したのに、また雨降ってきた。最悪。", furigana: "せっかく洗[せん]車[しゃ]したのに、また雨[あめ]降[ふ]ってきた。最[さい]悪[あく]。", translation: "難得洗了車，結果又下雨了。超慘。", tags: ["N3", "常體"] }, { speaker: "朋友", role: "staff", text: "まあ、そういう時もあるよ。しょうがないね。", furigana: "まあ、そういう時[とき]もあるよ。しょうがないね。", translation: "嘛，也是會有這種時候啦。沒辦法呢。", tags: ["N4", "常體"] } ] },

  // 🍻 交友休閒 - 社群互動 (10)
  { category: "社群互動", title: "交換聯絡方式", icon: "📱", description: "初次見面的新朋友加LINE", dialogues: [ { speaker: "主角", role: "user", text: "もしよかったら、LINE交換しない？", furigana: "もしよかったら、LINE交[こう]換[かん]しない？", translation: "如果不介意的話，要不要交換個LINE？", tags: ["N5", "常體"] }, { speaker: "朋友", role: "staff", text: "うん、いいよ。QRコード出すね。", furigana: "うん、いいよ。QRコード出[だ]すね。", translation: "嗯，好啊。我把條碼叫出來喔。", tags: ["N5", "常體"] } ] },
  { category: "社群互動", title: "討論網路話題", icon: "🌐", description: "聊最近爆紅的YouTube影片", dialogues: [ { speaker: "主角", role: "user", text: "最近バズってるあの動画、もう見た？", furigana: "最[さい]近[きん]バズってるあの動[どう]画[が]、もう見[み]た？", translation: "最近爆紅的那個影片，你看過了嗎？", tags: ["N3", "常體", "網路用語"] }, { speaker: "朋友", role: "staff", text: "見た見た！めっちゃ面白くて何回もリピートしちゃった。", furigana: "見[み]た見[み]た！めっちゃ面[おも]白[しろ]くて何[なん]回[かい]もリピートしちゃった。", translation: "看了看了！超級有趣，我忍不住重播了好幾次。", tags: ["N4", "常體"] } ] },
  { category: "社群互動", title: "留言互動", icon: "💬", description: "看到朋友IG打卡的回覆", dialogues: [ { speaker: "主角", role: "user", text: "昨日のインスタの写真、どこ？すごくおしゃれ！", furigana: "昨[きのう]日[のう]のインスタの写[しゃ]真[しん]、どこ？すごくおしゃれ！", translation: "昨天IG上的照片是哪裡？超有氣氛的！", tags: ["N4", "常體"] }, { speaker: "朋友", role: "staff", text: "表参道に新しくできたカフェだよ。今度一緒に行こうよ！", furigana: "表[おもて]参[さん]道[どう]に新[あたら]しくできたカフェだよ。今[こん]度[ど]一[いっ]緒[しょ]に行[い]こうよ！", translation: "那是表參道新開的咖啡廳喔。下次一起去吧！", tags: ["N4", "常體"] } ] },
  { category: "社群互動", title: "詢問是否能發照片", icon: "📷", description: "把合照PO上網前的確認", dialogues: [ { speaker: "主角", role: "user", text: "さっき撮った写真、インスタのストーリーに上げてもいい？", furigana: "さっき撮[と]った写[しゃ]真[しん]、インスタのストーリーに上[あ]げてもいい？", translation: "剛剛拍的照片，我可以發到IG限時動態上嗎？", tags: ["N4", "常體", "網路用語"] }, { speaker: "朋友", role: "staff", text: "いいよ！あ、でも私のアカウントもタグ付けしてね！", furigana: "いいよ！あ、でも私[わたし]のアカウントもタグ付[づ]けしてね！", translation: "可以啊！啊，不過要記得標記(Tag)我的帳號喔！", tags: ["N4", "常體"] } ] },
  { category: "社群互動", title: "已讀不回的抱怨", icon: "📱", description: "朋友看了訊息卻不回", dialogues: [ { speaker: "主角", role: "user", text: "ねえ、昨日のLINE、既読スルーしたでしょ！", furigana: "ねえ、昨[きのう]日[のう]のLINE、既[き]読[どく]スルーしたでしょ！", translation: "欸，你昨天把我LINE已讀不回對吧！", tags: ["N3", "常體", "網路用語"] }, { speaker: "朋友", role: "staff", text: "あ！ごめん、後で返信しようと思ってて、完全に忘れてた。", furigana: "あ！ごめん、後[あと]で返[へん]信[しん]しようと思[おも]ってて、完[かん]全[ぜん]に忘[わす]れてた。", translation: "啊！抱歉，我本來想說晚點回，結果完全忘記了。", tags: ["N4", "常體"] } ] },
  { category: "社群互動", title: "訊息收回", icon: "🔙", description: "傳錯訊息趕緊收回", dialogues: [ { speaker: "朋友", role: "staff", text: "あれ？さっき送信取り消ししたメッセージ、何だったの？", furigana: "あれ？さっき送[そう]信[しん]取[と]り消[け]ししたメッセージ、何[なん]だったの？", translation: "咦？剛剛你收回的訊息是什麼？", tags: ["N4", "常體"] }, { speaker: "主角", role: "user", text: "あ、ううん。別の人に送るやつを間違えて送っちゃっただけ。", furigana: "あ、ううん。別[べつ]の人[ひと]に送[おく]るやつを間[ま]違[ちが]えて送[おく]っちゃっただけ。", translation: "啊，沒事。只是把要傳給別人的訊息傳錯了而已。", tags: ["N4", "常體"] } ] },
  { category: "社群互動", title: "求關注/點讚", icon: "👍", description: "發了新貼文叫朋友去看", dialogues: [ { speaker: "主角", role: "user", text: "新しい動画アップしたから、いいねとチャンネル登録よろしく！", furigana: "新[あたら]しい動[どう]画[が]アップしたから、いいねとチャンネル登[とう]録[ろく]よろしく！", translation: "我上傳新影片了，記得幫我按讚跟訂閱頻道喔！", tags: ["N4", "常體", "網路用語"] }, { speaker: "朋友", role: "staff", text: "もう見たよ！ちゃんと高評価押しといたからね。", furigana: "もう見[み]たよ！ちゃんと高[こう]評[ひょう]価[か]押[お]しといたからね。", translation: "我已經看啦！我有好好幫你按讚(高評價)了喔。", tags: ["N4", "常體"] } ] },
  { category: "社群互動", title: "封鎖對方", icon: "🚫", description: "遇到奇怪的網友或前任", dialogues: [ { speaker: "主角", role: "user", text: "元カレからしつこく連絡が来るから、LINEブロックしちゃった。", furigana: "元[もと]カレからしつこく連[れん]絡[らく]が来[く]るから、LINEブロックしちゃった。", translation: "前男友一直死纏爛打聯絡我，我就把他的LINE封鎖了。", tags: ["N3", "常體"] }, { speaker: "朋友", role: "staff", text: "それが正解だよ！関わらない方がいいって。", furigana: "それが正[せい]解[かい]だよ！関[かか]わらない方[ほう]がいいって。", translation: "那才是正確答案！不要跟他扯上關係比較好。", tags: ["N3", "常體"] } ] },
  { category: "社群互動", title: "群組通話", icon: "📞", description: "跟一群朋友用語音聊天", dialogues: [ { speaker: "主角", role: "user", text: "もしもし？私の声、ちゃんと聞こえてる？", furigana: "もしもし？私[わたし]の声[こえ]、ちゃんと聞[き]こえてる？", translation: "喂喂？你們有清楚聽到我的聲音嗎？", tags: ["N5", "常體"] }, { speaker: "朋友", role: "staff", text: "うん、聞こえてるよ！でも、ちょっと後ろの雑音がうるさいかも。", furigana: "うん、聞[き]こえてるよ！でも、ちょっと後[うし]ろの雑[ざつ]音[おん]がうるさいかも。", translation: "嗯，有聽到喔！不過你後面的背景雜音好像有點吵。", tags: ["N4", "常體"] } ] },
  { category: "社群互動", title: "分享迷因圖", icon: "😂", description: "傳好笑的梗圖給朋友", dialogues: [ { speaker: "主角", role: "user", text: "この画像、めっちゃウケるんだけど！見てみて！", furigana: "この画[が]像[ぞう]、めっちゃウケるんだけど！見[み]てみて！", translation: "這張圖超級好笑的啦！你看你看！", tags: ["N3", "常體", "流行語"] }, { speaker: "朋友", role: "staff", text: "草。これ誰が作ったの？センスありすぎ！", furigana: "草[くさ]。これ誰[だれ]が作[つく]ったの？センスありすぎ！", translation: "笑死(草)。這是誰做的啊？太有品味了吧！", tags: ["N3", "常體", "網路用語"] } ] }
];

const dbPath = 'c:/ai/jlpt_data_export.json';
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

data.forEach((item, index) => {
  item.id = `conv_social_mass_${index}`;
  item.stage = "🍻 交友休閒 (Friends & Leisure)";
  db.JLPT_DATA.conversations.push(item);
});

fs.writeFileSync(dbPath, JSON.stringify(db, null, 2), 'utf8');
console.log(`Injected ${data.length} Massive Social scenarios.`);
